"""Minimal local Ollama client used for non-scoring explanations."""

import json
from urllib.error import URLError
from urllib.request import Request, urlopen

from app.core.config import get_settings


class OllamaClient:
    """Calls a local Ollama server. Scores are never generated by this client."""

    def generate_json(self, prompt: str) -> dict[str, object]:
        settings = get_settings()
        if not settings.ollama_enabled:
            raise RuntimeError("Ollama is disabled.")
        request = Request(
            f"{settings.ollama_base_url.rstrip('/')}/api/generate",
            data=json.dumps({"model": settings.ollama_model, "prompt": prompt, "stream": False, "format": "json", "options": {"temperature": 0.2}}).encode("utf-8"),
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        try:
            # A local model can take longer on its first request while it loads
            # into memory, especially on a laptop without a discrete GPU.
            with urlopen(request, timeout=120) as response:  # noqa: S310 - configured local service
                payload = json.loads(response.read().decode("utf-8"))
        except URLError as exc:
            raise RuntimeError("Ollama is not running locally.") from exc
        content = payload.get("response")
        if not isinstance(content, str):
            raise RuntimeError("Ollama returned no explanation.")
        result = json.loads(content)
        if not isinstance(result, dict):
            raise RuntimeError("Ollama did not return a JSON object.")
        return result

    def generate_text(self, prompt: str) -> str:
        """Return a normal text response for the context-aware advisor chat."""
        settings = get_settings()
        if not settings.ollama_enabled:
            raise RuntimeError("Ollama is disabled.")
        request = Request(
            f"{settings.ollama_base_url.rstrip('/')}/api/generate",
            data=json.dumps({"model": settings.ollama_model, "prompt": prompt, "stream": False, "options": {"temperature": 0.35}}).encode("utf-8"),
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        try:
            # Keep the advisor available while Ollama performs its first model load.
            with urlopen(request, timeout=120) as response:  # noqa: S310 - configured local service
                payload = json.loads(response.read().decode("utf-8"))
        except URLError as exc:
            raise RuntimeError("Ollama is not running locally.") from exc
        content = payload.get("response")
        if not isinstance(content, str) or not content.strip():
            raise RuntimeError("Ollama returned no advisor response.")
        return content.strip()
