"""Profile-aware Gemini advice with auditable conversation persistence."""

import logging

from sqlalchemy import select
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.orm import Session

from app.ai.gemini_client import GeminiClient
from app.ai.ollama_client import OllamaClient
from app.core.config import get_settings
from app.core.exceptions import ResourceNotFoundError
from app.models.chat import ChatConversation, ChatMessage
from app.models.lifecycle import LifecycleFinancialPlan, LifecycleRiskAssessment, StartupProfile
from app.models.user import User

logger = logging.getLogger(__name__)


class LifecycleAdvisorService:
    def __init__(self, session: Session) -> None:
        self.session = session

    def ask(self, user: User, profile_id: str, question: str, conversation_id: str | None = None) -> tuple[str, str, str, str | None]:
        profile = self.session.get(StartupProfile, profile_id)
        if not profile or profile.created_by_id != user.id:
            raise ResourceNotFoundError("Startup profile was not found.")

        # Risk and finance enrich the prompt, but an older development database
        # must not prevent a founder from using the AI Advisor.  This is useful
        # while a migration is being applied to optional lifecycle tables.
        try:
            risk = self.session.scalar(select(LifecycleRiskAssessment).where(
                LifecycleRiskAssessment.startup_profile_id == profile_id
            ).order_by(LifecycleRiskAssessment.created_at.desc()))
        except SQLAlchemyError as exc:
            logger.warning("Could not load optional risk context for advisor profile %s: %s", profile_id, exc)
            self.session.rollback()
            risk = None
        try:
            plan = self.session.scalar(select(LifecycleFinancialPlan).where(
                LifecycleFinancialPlan.startup_profile_id == profile_id
            ).order_by(LifecycleFinancialPlan.created_at.desc()))
        except SQLAlchemyError as exc:
            logger.warning("Could not load optional financial context for advisor profile %s: %s", profile_id, exc)
            self.session.rollback()
            plan = None

        conversation = self._conversation(user, profile, conversation_id)
        history = list(self.session.scalars(
            select(ChatMessage).where(ChatMessage.conversation_id == conversation.id).order_by(ChatMessage.sequence_number)
        ))
        sequence = len(history) + 1
        self.session.add(ChatMessage(
            conversation_id=conversation.id, sequence_number=sequence, role="user", content=question,
            context_metadata={"startup_profile_id": profile_id},
        ))
        prompt = self._prompt(profile, risk, plan, history[-6:], question)
        mode, notice = "ollama", None
        try:
            answer = OllamaClient().generate_text(prompt)
        except Exception as exc:
            logger.warning("Ollama advisor unavailable for profile %s: %s", profile_id, exc)
            if get_settings().gemini_api_key:
                try:
                    mode = "gemini"
                    answer = GeminiClient().generate(prompt)
                    notice = "Guidance generated by the configured Gemini service."
                except Exception as gemini_exc:
                    logger.warning("Gemini advisor unavailable for profile %s: %s", profile_id, gemini_exc)
                    mode = "structured_fallback"
                    notice = "Local AI and Gemini are unavailable. This is a structured response from your saved VentureMind data."
                    answer = self._fallback(profile, risk, plan, question)
            else:
                mode = "structured_fallback"
                notice = "Local AI is unavailable. This is a structured response from your saved VentureMind data."
                answer = self._fallback(profile, risk, plan, question)

        self.session.add(ChatMessage(
            conversation_id=conversation.id, sequence_number=sequence + 1, role="assistant", content=answer,
            model=get_settings().ollama_model if mode == "ollama" else get_settings().gemini_model if mode == "gemini" else "venturemind-structured-fallback",
            context_metadata={"startup_profile_id": profile_id, "mode": mode},
        ))
        self.session.commit()
        return conversation.id, answer, mode, notice

    def ask_without_persistence(self, user: User, profile_id: str, question: str) -> tuple[str, str, str, str | None]:
        """Generate local, profile-aware guidance without relying on chat tables.

        This keeps the real Ollama feature usable when a development database has
        older chat-conversation columns or an incomplete chat migration. The
        standard ``ask`` method remains the persisted-chat implementation.
        """
        profile = self.session.get(StartupProfile, profile_id)
        if not profile or profile.created_by_id != user.id:
            raise ResourceNotFoundError("Startup profile was not found.")

        try:
            risk = self.session.scalar(select(LifecycleRiskAssessment).where(
                LifecycleRiskAssessment.startup_profile_id == profile_id
            ).order_by(LifecycleRiskAssessment.created_at.desc()))
        except SQLAlchemyError as exc:
            logger.warning("Could not load optional risk context for local advisor profile %s: %s", profile_id, exc)
            self.session.rollback()
            risk = None
        try:
            plan = self.session.scalar(select(LifecycleFinancialPlan).where(
                LifecycleFinancialPlan.startup_profile_id == profile_id
            ).order_by(LifecycleFinancialPlan.created_at.desc()))
        except SQLAlchemyError as exc:
            logger.warning("Could not load optional financial context for local advisor profile %s: %s", profile_id, exc)
            self.session.rollback()
            plan = None

        try:
            answer = OllamaClient().generate_text(self._prompt(profile, risk, plan, [], question))
            return "local-ollama-session", answer, "ollama", "Guidance generated locally by VentureMind AI."
        except Exception as exc:
            logger.warning("Ollama quick advisor unavailable for profile %s: %s", profile_id, exc)
            return "local-structured-session", self._fallback(profile, risk, plan, question), "structured_fallback", "Local AI is unavailable. This is structured guidance from your saved VentureMind data."

    def _conversation(self, user: User, profile: StartupProfile, conversation_id: str | None) -> ChatConversation:
        conversation = self.session.get(ChatConversation, conversation_id) if conversation_id else None
        if conversation and (conversation.user_id != user.id or conversation.project_id is not None):
            raise ResourceNotFoundError("Advisor conversation was not found.")
        if conversation:
            return conversation
        conversation = ChatConversation(user_id=user.id, title=f"Advisor: {profile.business_name}")
        self.session.add(conversation)
        self.session.flush()
        return conversation

    @staticmethod
    def _prompt(profile: StartupProfile, risk: LifecycleRiskAssessment | None, plan: LifecycleFinancialPlan | None, history: list[ChatMessage], question: str) -> str:
        transcript = "\n".join(f"{message.role.title()}: {message.content}" for message in history)
        context = {
            "business": profile.business_name,
            "category": profile.category,
            "description": profile.description,
            "target_customers": profile.target_customers,
            "location": ", ".join(item for item in [profile.city, profile.district, profile.country] if item),
            "business_goals": profile.business_goals,
            "expected_investment": str(profile.expected_investment) if profile.expected_investment is not None else "not recorded",
            "available_budget": str(profile.available_budget) if profile.available_budget is not None else "not recorded",
            "business_experience": profile.business_experience or "not recorded",
            "launch_timeline": profile.launch_timeline or "not recorded",
            "team_plan": {"partners": profile.partner_count, "employees": profile.expected_employees},
            "risk_score": str(risk.overall_risk_score) if risk else "not assessed",
            "risk_recommendations": risk.recommendations if risk else "Run risk analysis first.",
            "financial_plan": plan.results if plan else "No financial plan created.",
        }
        return (
            "You are VentureMind AI, a practical and concise startup business mentor. Use only the supplied context. "
            "Do not invent facts, competitors, pricing, laws, or market statistics. Do not guarantee outcomes. "
            "State any missing evidence, then give exactly three practical next actions.\n"
            f"Saved founder context: {context}\n"
            f"Recent conversation: {transcript or 'No prior messages.'}\n"
            f"Founder question: {question}"
        )

    @staticmethod
    def _fallback(profile: StartupProfile, risk: LifecycleRiskAssessment | None, plan: LifecycleFinancialPlan | None, question: str) -> str:
        first_risk = "Complete the risk analysis to identify the highest-priority assumption."
        if risk and risk.recommendations:
            first_risk = str(risk.recommendations[0].get("recommendation", first_risk))
        finance_action = "Create a financial plan with monthly costs, expected revenue, and an emergency buffer."
        if plan:
            finance_action = "Review the saved financial plan and test its revenue and cost assumptions with real quotes or customer evidence."
        location = ", ".join(dict.fromkeys(item for item in [profile.city, profile.district, profile.country] if item)) or "the selected market"
        customers = profile.target_customers or "a target customer group that still needs to be defined"
        description = profile.description or "the business offer"
        profile_summary = f"{profile.business_name} · {profile.category} · {location}"
        return (
            f"Focus first: validate customer demand and price for {profile.business_name}.\n\n"
            f"Why this matters\nYour saved profile describes {description} for {customers} in {location}. "
            "Before spending more, confirm that this group has the problem and will pay for your offer.\n\n"
            "Recommended next actions\n"
            f"1. {first_risk}\n"
            f"2. Interview 10 target customers. Ask what they use now, what they dislike, and what price feels acceptable.\n"
            f"3. {finance_action}\n\n"
            f"Context used: {profile_summary}\n"
            "Mode: structured guidance from your saved VentureMind data (Gemini is currently unavailable)."
        )
