import { useEffect, useState } from 'react'
import type { AxiosError } from 'axios'
import { apiClient } from '@/api/client'
import { Button } from '@/components/common/Button'
import type { APIResponse } from '@/types/api'

type Slot = { id: string; starts_at: string; ends_at: string; consultation_type: 'online' | 'in_person'; is_booked: boolean }
export function AdvisorAvailabilityPage() {
  const [slots, setSlots] = useState<Slot[]>([]); const [start, setStart] = useState(''); const [end, setEnd] = useState(''); const [kind, setKind] = useState<'online' | 'in_person'>('online'); const [error, setError] = useState('')
  const load = async () => { try { const response = await apiClient.get<APIResponse<Slot[]>>('/human-advisors/availability-slots/mine'); setSlots(response.data.data) } catch (requestError) { const error = requestError as AxiosError<{ detail?: string }>; setError(error.response?.status ? `Availability could not be loaded (${error.response.status}). ${error.response.data?.detail ?? 'Apply the latest database migration.'}` : 'Availability could not be loaded. Confirm the backend is running and this account is an approved advisor.') } }
  useEffect(() => { void load() }, [])
  const add = async () => { if (new Date(start) <= new Date() || new Date(end) <= new Date(start)) { setError('Choose a future end time that is later than the start time.'); return } try { await apiClient.post('/human-advisors/availability-slots', { starts_at: new Date(start).toISOString(), ends_at: new Date(end).toISOString(), consultation_type: kind }); setError(''); setStart(''); setEnd(''); await load() } catch (requestError) { const error = requestError as AxiosError<{ detail?: string }>; setError(error.response?.status ? `The appointment slot could not be saved (${error.response.status}). ${error.response.data?.detail ?? 'Apply the latest database migration.'}` : 'The backend could not save this appointment slot. Confirm it is running.') } }
  const remove = async (id: string) => { try { await apiClient.delete(`/human-advisors/availability-slots/${id}`); await load() } catch { setError('Booked slots cannot be removed.') } }
  return <div className="mx-auto max-w-4xl space-y-6"><header><p className="page-eyebrow">Advisor schedule</p><h1 className="page-title">Manage available appointments</h1><p className="mt-2 text-sm text-slate-600">Founders can reserve only these published times. Booked slots stay protected from double booking.</p></header>{error && <p className="rounded-xl bg-rose-50 p-4 text-sm text-rose-800">{error}</p>}<section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-card"><div className="grid gap-4 md:grid-cols-3"><label className="text-sm font-semibold">Start<input type="datetime-local" value={start} onChange={(e) => setStart(e.target.value)} className="mt-2 w-full rounded-lg border p-3" /></label><label className="text-sm font-semibold">End<input type="datetime-local" value={end} onChange={(e) => setEnd(e.target.value)} className="mt-2 w-full rounded-lg border p-3" /></label><label className="text-sm font-semibold">Type<select value={kind} onChange={(e) => setKind(e.target.value as typeof kind)} className="mt-2 w-full rounded-lg border p-3"><option value="online">Online</option><option value="in_person">In person</option></select></label></div><Button className="mt-4" disabled={!start || !end} onClick={() => void add()}>Add appointment slot</Button></section><section className="grid gap-3 md:grid-cols-2">{slots.map((slot) => <article key={slot.id} className="rounded-xl border bg-white p-4 shadow-card"><strong>{new Date(slot.starts_at).toLocaleString()}</strong><p className="mt-1 text-sm text-slate-600">{slot.consultation_type.replace('_', ' ')} · ends {new Date(slot.ends_at).toLocaleTimeString()}</p><div className="mt-3 flex items-center justify-between"><span className="text-xs font-bold">{slot.is_booked ? 'Reserved' : 'Available'}</span>{!slot.is_booked && <Button variant="ghost" className="text-xs text-rose-700" onClick={() => void remove(slot.id)}>Remove</Button>}</div></article>)}</section></div>
}
