import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'

const calculators = [
  { title: 'Startup Cost Calculator', description: 'Estimate one-time launch costs plus a 12-month operating plan.', to: '/calculators/startup-cost', time: '~2 min' },
  { title: 'Break-Even Calculator', description: 'Estimate the number of sales and revenue needed to cover fixed costs.', to: '/calculators/break-even', time: '~1 min' },
  { title: 'Startup Runway Calculator', description: 'Estimate how many months your available cash can support the current burn rate.', to: '/calculators/runway', time: '~1 min' },
  { title: 'ROI Calculator', description: 'Estimate return on investment and the profit generated by a spend.', to: '/calculators/roi', time: '~1 min' },
  { title: 'CAC Calculator', description: 'Estimate the cost of acquiring one customer from a campaign or channel.', to: '/calculators/cac', time: '~1 min' },
  { title: 'LTV Calculator', description: 'Estimate customer lifetime value from recurring revenue, margin, and retention.', to: '/calculators/ltv', time: '~2 min' },
  { title: 'Market Size Calculator', description: 'Estimate TAM, SAM, and SOM from customers, annual spend, and your reachable share.', to: '/calculators/market-size', time: '~3 min' },
  { title: 'Funding Calculator', description: 'Estimate the capital needed to support a target runway at your planned burn rate.', to: '/calculators/funding', time: '~2 min' },
  { title: 'Equity Dilution Calculator', description: 'Estimate investor and founder ownership after one financing round.', to: '/calculators/equity-dilution', time: '~2 min' },
  { title: 'Startup Valuation Calculator', description: 'Explore a revenue-multiple valuation scenario using your own assumptions.', to: '/calculators/valuation', time: '~2 min' },
]

function money(value: number) {
  return new Intl.NumberFormat(undefined, { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(Number.isFinite(value) ? value : 0)
}

function NumberField({ label, value, onChange, help }: { label: string; value: number; onChange: (value: number) => void; help?: string }) {
  return <label className="block text-sm font-semibold">{label}<input min="0" value={value} onChange={(event) => onChange(Math.max(0, Number(event.target.value)))} className="mt-2 w-full rounded-lg border border-slate-300 bg-transparent p-3 font-normal dark:border-slate-700" type="number" />{help && <span className="mt-1 block text-xs font-normal text-slate-500">{help}</span>}</label>
}

export function CalculatorsDirectoryPage() {
  return <div className="-mx-4 -my-8 sm:-mx-6"><section className="bg-gradient-to-br from-brand-50 via-white to-accent-50 px-4 py-20 text-center dark:from-slate-950 dark:via-slate-950 dark:to-slate-900 sm:px-6"><p className="text-sm font-bold uppercase tracking-widest text-brand-600">Founder calculators</p><h1 className="mt-4 text-4xl font-bold tracking-tight sm:text-6xl">Turn a startup assumption into a number.</h1><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-slate-600 dark:text-slate-300">Free, browser-based calculations for early planning. Your inputs stay in this browser and are not saved by VentureMind.</p></section><section className="px-4 py-20 sm:px-6"><div className="mx-auto grid max-w-6xl gap-5 md:grid-cols-3">{calculators.map((calculator) => <article key={calculator.title} className="flex min-h-[260px] flex-col rounded-2xl border border-slate-200 bg-white p-6 shadow-card dark:border-slate-800 dark:bg-slate-900"><p className="text-xs font-bold uppercase tracking-widest text-brand-600">Free · {calculator.time}</p><h2 className="mt-4 text-xl font-bold">{calculator.title}</h2><p className="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-300">{calculator.description}</p><Link className="mt-auto pt-6 text-sm font-bold text-brand-600 hover:underline" to={calculator.to}>Open calculator →</Link></article>)}</div><p className="mx-auto mt-10 max-w-3xl text-center text-sm leading-6 text-slate-500">These calculators are planning aids, not financial, legal, or investment advice. Currency is shown in USD for consistency; use values appropriate to your market.</p></section></div>
}

type CalculatorKind = 'startup-cost' | 'break-even' | 'runway' | 'roi' | 'cac' | 'ltv' | 'market-size' | 'funding' | 'equity-dilution' | 'valuation'

export function CalculatorPage({ kind }: { kind: CalculatorKind }) {
  const [oneTime, setOneTime] = useState(3000)
  const [monthly, setMonthly] = useState(800)
  const [fixedCosts, setFixedCosts] = useState(2000)
  const [salePrice, setSalePrice] = useState(50)
  const [variableCost, setVariableCost] = useState(15)
  const [cash, setCash] = useState(12000)
  const [burn, setBurn] = useState(1500)
  const [investment, setInvestment] = useState(1000)
  const [returnValue, setReturnValue] = useState(1500)
  const [marketingSpend, setMarketingSpend] = useState(1200)
  const [salesSpend, setSalesSpend] = useState(800)
  const [newCustomers, setNewCustomers] = useState(40)
  const [monthlyRevenue, setMonthlyRevenue] = useState(40)
  const [grossMargin, setGrossMargin] = useState(70)
  const [monthlyChurn, setMonthlyChurn] = useState(5)
  const [marketCustomers, setMarketCustomers] = useState(100000)
  const [annualSpend, setAnnualSpend] = useState(300)
  const [serviceablePercent, setServiceablePercent] = useState(20)
  const [reachablePercent, setReachablePercent] = useState(2)
  const [targetRunway, setTargetRunway] = useState(18)
  const [oneTimeNeed, setOneTimeNeed] = useState(5000)
  const [preMoneyValuation, setPreMoneyValuation] = useState(1000000)
  const [investmentAmount, setInvestmentAmount] = useState(200000)
  const [annualRevenue, setAnnualRevenue] = useState(100000)
  const [revenueMultiple, setRevenueMultiple] = useState(4)
  const content = useMemo(() => {
    if (kind === 'startup-cost') return { title: 'Startup Cost Calculator', description: 'Estimate your launch cost and the operating cash needed for the first 12 months.', formula: 'Total 12-month funding need = one-time costs + (monthly operating costs × 12)', result: money(oneTime + monthly * 12), label: 'Estimated first-year funding need' }
    if (kind === 'break-even') {
      const contribution = salePrice - variableCost
      const units = contribution > 0 ? Math.ceil(fixedCosts / contribution) : 0
      return { title: 'Break-Even Calculator', description: 'Estimate how many sales are needed before your revenue covers your fixed costs.', formula: 'Break-even units = fixed monthly costs ÷ (sale price − variable cost per sale)', result: contribution > 0 ? `${units.toLocaleString()} units` : 'Set a price above the variable cost', label: contribution > 0 ? `Equivalent revenue: ${money(units * salePrice)}` : 'Contribution margin must be positive' }
    }
    if (kind === 'roi') {
      const roi = investment > 0 ? ((returnValue - investment) / investment) * 100 : 0
      return { title: 'ROI Calculator', description: 'Estimate the return generated by an investment, campaign, or other business spend.', formula: 'ROI = (return value − investment cost) ÷ investment cost × 100', result: `${roi.toFixed(1)}%`, label: `Net profit from this spend: ${money(returnValue - investment)}` }
    }
    if (kind === 'cac') {
      const totalSpend = marketingSpend + salesSpend
      const cac = newCustomers > 0 ? totalSpend / newCustomers : 0
      return { title: 'CAC Calculator', description: 'Estimate how much it costs to acquire one new customer through a campaign or channel.', formula: 'CAC = (marketing spend + sales spend) ÷ new customers acquired', result: newCustomers > 0 ? money(cac) : 'Enter new customers', label: `Based on ${money(totalSpend)} total acquisition spend` }
    }
    if (kind === 'ltv') {
      const margin = grossMargin / 100
      const churn = monthlyChurn / 100
      const ltv = churn > 0 ? (monthlyRevenue * margin) / churn : 0
      return { title: 'LTV Calculator', description: 'Estimate the gross profit a typical customer contributes across their expected lifetime.', formula: 'LTV = monthly revenue × gross margin ÷ monthly churn rate', result: churn > 0 ? money(ltv) : 'Enter a churn rate', label: churn > 0 ? `Estimated customer lifetime: ${(1 / churn).toFixed(1)} months` : 'Monthly churn must be greater than zero' }
    }
    if (kind === 'market-size') {
      const tam = marketCustomers * annualSpend
      const sam = tam * (serviceablePercent / 100)
      const som = sam * (reachablePercent / 100)
      return { title: 'Market Size Calculator', description: 'Estimate your total, serviceable, and initially obtainable market using your own assumptions.', formula: 'TAM = total customers × annual spend; SAM = TAM × serviceable share; SOM = SAM × reachable share', result: money(som), label: `TAM: ${money(tam)} · SAM: ${money(sam)} · SOM: ${money(som)}` }
    }
    if (kind === 'funding') {
      const raise = burn * targetRunway + oneTimeNeed
      return { title: 'Funding Calculator', description: 'Estimate a starting funding target based on operating burn, desired runway, and one-time requirements.', formula: 'Funding target = monthly net burn × target runway (months) + one-time funding needs', result: money(raise), label: `${targetRunway} months of runway at ${money(burn)} monthly burn` }
    }
    if (kind === 'equity-dilution') {
      const postMoney = preMoneyValuation + investmentAmount
      const investorShare = postMoney > 0 ? (investmentAmount / postMoney) * 100 : 0
      const founderShare = 100 - investorShare
      return { title: 'Equity Dilution Calculator', description: 'Estimate ownership after one investment round, before option pools or later financing rounds.', formula: 'Investor ownership = investment ÷ post-money valuation; post-money valuation = pre-money valuation + investment', result: `${investorShare.toFixed(1)}%`, label: `Investor ownership; founders retain ${founderShare.toFixed(1)}% (post-money: ${money(postMoney)})` }
    }
    if (kind === 'valuation') {
      const valuation = annualRevenue * revenueMultiple
      return { title: 'Startup Valuation Calculator', description: 'Explore a simple revenue-multiple valuation scenario using assumptions you set.', formula: 'Indicative valuation = annual revenue × selected revenue multiple', result: money(valuation), label: `Based on ${money(annualRevenue)} annual revenue and a ${revenueMultiple.toFixed(1)}× multiple` }
    }
    const months = burn > 0 ? cash / burn : 0
    return { title: 'Startup Runway Calculator', description: 'Estimate how long the cash you have available will last at your current monthly burn rate.', formula: 'Runway (months) = available cash ÷ monthly net burn', result: burn > 0 ? `${months.toFixed(1)} months` : 'Enter a monthly burn rate', label: burn > 0 ? `At a monthly burn of ${money(burn)}` : 'Monthly burn must be greater than zero' }
  }, [kind, oneTime, monthly, fixedCosts, salePrice, variableCost, cash, burn, investment, returnValue, marketingSpend, salesSpend, newCustomers, monthlyRevenue, grossMargin, monthlyChurn, marketCustomers, annualSpend, serviceablePercent, reachablePercent, targetRunway, oneTimeNeed, preMoneyValuation, investmentAmount, annualRevenue, revenueMultiple])

  const fields = kind === 'startup-cost' ? <><NumberField label="One-time launch costs" value={oneTime} onChange={setOneTime} help="Setup, equipment, initial design, legal, or launch costs."/><NumberField label="Monthly operating costs" value={monthly} onChange={setMonthly} help="People, software, rent, marketing, and other monthly costs."/></> : kind === 'break-even' ? <><NumberField label="Fixed monthly costs" value={fixedCosts} onChange={setFixedCosts}/><NumberField label="Average sale price" value={salePrice} onChange={setSalePrice}/><NumberField label="Variable cost per sale" value={variableCost} onChange={setVariableCost} help="Costs that increase with each unit sold, such as fulfilment or transaction fees."/></> : kind === 'roi' ? <><NumberField label="Investment cost" value={investment} onChange={setInvestment}/><NumberField label="Return value" value={returnValue} onChange={setReturnValue} help="Revenue or value directly attributed to this investment."/></> : kind === 'cac' ? <><NumberField label="Marketing spend" value={marketingSpend} onChange={setMarketingSpend}/><NumberField label="Sales spend" value={salesSpend} onChange={setSalesSpend}/><NumberField label="New customers acquired" value={newCustomers} onChange={setNewCustomers}/></> : kind === 'ltv' ? <><NumberField label="Monthly revenue per customer" value={monthlyRevenue} onChange={setMonthlyRevenue}/><NumberField label="Gross margin (%)" value={grossMargin} onChange={setGrossMargin}/><NumberField label="Monthly churn (%)" value={monthlyChurn} onChange={setMonthlyChurn} help="Percentage of customers lost each month."/></> : kind === 'market-size' ? <><NumberField label="Total potential customers" value={marketCustomers} onChange={setMarketCustomers}/><NumberField label="Annual spend per customer" value={annualSpend} onChange={setAnnualSpend}/><NumberField label="Serviceable share (%)" value={serviceablePercent} onChange={setServiceablePercent} help="The percentage of the total market your solution can serve."/><NumberField label="Reachable share (%)" value={reachablePercent} onChange={setReachablePercent} help="The percentage of your serviceable market you expect to reach initially."/></> : kind === 'funding' ? <><NumberField label="Monthly net burn" value={burn} onChange={setBurn}/><NumberField label="Target runway (months)" value={targetRunway} onChange={setTargetRunway}/><NumberField label="One-time funding needs" value={oneTimeNeed} onChange={setOneTimeNeed} help="Initial equipment, setup, launch, or other non-recurring needs."/></> : kind === 'equity-dilution' ? <><NumberField label="Pre-money valuation" value={preMoneyValuation} onChange={setPreMoneyValuation}/><NumberField label="Investment amount" value={investmentAmount} onChange={setInvestmentAmount}/></> : kind === 'valuation' ? <><NumberField label="Annual revenue" value={annualRevenue} onChange={setAnnualRevenue}/><NumberField label="Revenue multiple" value={revenueMultiple} onChange={setRevenueMultiple} help="A scenario assumption, not a market benchmark or investment advice."/></> : <><NumberField label="Available cash" value={cash} onChange={setCash}/><NumberField label="Monthly net burn" value={burn} onChange={setBurn} help="Monthly cash outflow after revenue."/></>
  return <div className="-mx-4 -my-8 sm:-mx-6"><section className="bg-slate-950 px-4 py-16 text-white sm:px-6"><div className="mx-auto max-w-5xl"><Link className="text-sm font-bold text-accent-300 hover:underline" to="/calculators">← All calculators</Link><p className="mt-8 text-sm font-bold uppercase tracking-widest text-accent-300">Free planning tool</p><h1 className="mt-3 text-4xl font-bold tracking-tight">{content.title}</h1><p className="mt-4 max-w-2xl text-lg leading-8 text-slate-300">{content.description}</p></div></section><section className="px-4 py-16 sm:px-6"><div className="mx-auto grid max-w-5xl gap-7 lg:grid-cols-[1fr_0.9fr]"><div className="space-y-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-float dark:border-slate-800 dark:bg-slate-900">{fields}</div><aside className="rounded-2xl bg-brand-600 p-7 text-white"><p className="text-sm font-bold uppercase tracking-widest text-brand-100">Your estimate</p><p className="mt-5 text-4xl font-bold">{content.result}</p><p className="mt-3 text-sm leading-6 text-brand-100">{content.label}</p><div className="mt-8 border-t border-white/20 pt-5"><p className="text-xs font-bold uppercase tracking-widest text-brand-100">Formula used</p><p className="mt-2 text-sm leading-6">{content.formula}</p></div></aside></div></section></div>
}
