import { Link } from 'react-router-dom'

const resources = [
  { number: '00', title: 'Founder knowledge hub', description: 'Search practical questions, topic guides, comparison frameworks, legal preparation, calculators, templates, and learning resources in one place.', action: 'Open knowledge hub', to: '/knowledge-hub', tone: 'bg-violet-50 text-violet-800' },
  { number: '01', title: 'Editable templates', description: 'Start with structured customer personas, interview questions, competitive analysis, lean canvas, business plan, and pitch-deck formats.', action: 'Browse templates', to: '/templates', tone: 'bg-sky-50 text-sky-800' },
  { number: '02', title: 'Startup stories', description: 'Study verified success and failure stories to understand customer demand, timing, product focus, and execution trade-offs.', action: 'Read stories', to: '/stories', tone: 'bg-amber-50 text-amber-800' },
  { number: '03', title: 'Founder library', description: 'Explore recommended startup books and practical learning material before choosing your next strategy.', action: 'Browse books', to: '/books', tone: 'bg-emerald-50 text-emerald-800' },
  { number: '04', title: 'Financial calculators', description: 'Estimate startup cost, break-even, runway, CAC, LTV, funding needs, valuation, and potential dilution.', action: 'Use calculators', to: '/calculators', tone: 'bg-rose-50 text-rose-800' },
  { number: '05', title: 'Explainable AI guide', description: 'Understand what VentureMind scores mean, which evidence contributes to them, and why results are decision support.', action: 'Learn about scoring', to: '/explainable-ai', tone: 'bg-indigo-50 text-indigo-800' },
]

const principles = [
  ['Start with evidence', 'Prioritise real customer behaviour, market data, quotes, and tests over assumptions.'],
  ['Reduce one risk at a time', 'Choose the highest-priority uncertainty and design the smallest useful experiment.'],
  ['Document your decisions', 'Keep your customer interviews, assumptions, costs, and outcomes in one startup workspace.'],
]

export function LearnPage() {
  return <div className="-mx-4 -my-8 sm:-mx-6"><section className="bg-gradient-to-br from-slate-950 via-brand-950 to-indigo-950 px-4 py-20 text-white sm:px-6"><div className="mx-auto max-w-5xl"><p className="text-sm font-bold uppercase tracking-widest text-accent-300">Founder learning hub</p><h1 className="mt-4 max-w-4xl text-4xl font-bold tracking-tight sm:text-6xl">Learn what to do before, during, and after your startup launch.</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-300">A practical resource library for customer discovery, market research, financial planning, legal preparation, and ongoing business decisions.</p><div className="mt-8 flex flex-wrap gap-3"><Link className="rounded-lg bg-white px-5 py-3 text-sm font-bold text-brand-700 hover:bg-brand-50" to="/templates">Browse templates</Link><Link className="rounded-lg border border-white/30 px-5 py-3 text-sm font-bold hover:bg-white/10" to="/calculators">Open calculators</Link></div></div></section>
    <section className="px-4 py-20 sm:px-6"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-widest text-brand-600">Learning library</p><h2 className="mt-3 text-3xl font-bold">Choose the resource that matches your current stage.</h2><p className="mt-3 leading-7 text-slate-600 dark:text-slate-300">Each collection has a different purpose, so you do not have to revisit the same validation screens.</p></div><div className="mt-10 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{resources.map((resource) => <article key={resource.title} className="flex min-h-64 flex-col rounded-2xl border border-slate-200 bg-white p-6 shadow-card transition hover:-translate-y-1 dark:border-slate-800 dark:bg-slate-900"><span className={`grid h-10 w-10 place-items-center rounded-xl text-sm font-extrabold ${resource.tone}`}>{resource.number}</span><h3 className="mt-5 text-xl font-bold">{resource.title}</h3><p className="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-300">{resource.description}</p><Link className="mt-auto pt-5 text-sm font-bold text-brand-600 hover:underline" to={resource.to}>{resource.action} →</Link></article>)}</div></div></section>
    <section className="bg-slate-100 px-4 py-20 dark:bg-slate-900/60 sm:px-6"><div className="mx-auto max-w-7xl"><p className="text-sm font-bold uppercase tracking-widest text-brand-600">How to use VentureMind responsibly</p><h2 className="mt-3 text-3xl font-bold">Use tools to make better decisions, not to skip the work.</h2><div className="mt-8 grid gap-5 md:grid-cols-3">{principles.map(([title, description], index) => <article key={title} className="rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-950"><p className="text-sm font-extrabold text-brand-600">0{index + 1}</p><h3 className="mt-4 text-lg font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-300">{description}</p></article>)}</div></div></section>
  </div>
}
