import { Link } from 'react-router-dom'

type LegalSection = { title: string; body: string }

const termsSections: LegalSection[] = [
  { title: '1. Purpose of VentureMind AI', body: 'VentureMind AI is an academic software project that helps founders organise startup information, assess assumptions, plan next steps, and request guidance from approved human advisors. It is decision support, not professional legal, financial, tax, investment, medical, or business advice.' },
  { title: '2. Accounts and responsible use', body: 'Users must provide accurate account information, protect their password, and use the platform lawfully. Do not upload harmful, unlawful, confidential third-party, or sensitive personal information unless you have permission and the feature specifically requires it.' },
  { title: '3. AI-generated guidance', body: 'AI outputs, including scores, recommendations, risk analyses, and generated documents, may contain errors or omissions. They are informative starting points only. Users remain responsible for validating information, obtaining professional advice where needed, and making their own business decisions.' },
  { title: '4. Human advisor services', body: 'Advisor profiles, appointments, requested documents, fees, and meeting details are managed through the platform workflow. VentureMind does not guarantee the outcome of a consultation. Users should independently verify an advisor’s qualifications and share only the documents requested for a legitimate consultation.' },
  { title: '5. Payments and demonstrations', body: 'Any payment, fee, earnings, or booking-payment screens currently shown in VentureMind are demonstration features unless a live payment provider is explicitly enabled. No payment should be treated as completed until a confirmed transaction record is displayed by the configured payment provider.' },
  { title: '6. Availability and changes', body: 'Features may be updated, paused, or removed while the project is developed and evaluated. These terms may be revised when the platform changes. Continued use after a published update means the user accepts the updated terms.' },
]

const privacySections: LegalSection[] = [
  { title: '1. Information the platform processes', body: 'VentureMind processes account information such as name, email address, role, and password hash; startup profile information; evaluations; advisor booking messages; and documents that a user deliberately uploads for a consultation. Technical logs may also be collected to operate and secure the system.' },
  { title: '2. Why information is used', body: 'Information is used to authenticate users, save startup plans, generate requested analyses, manage appointments and advisor communications, produce reports, and maintain platform security. The platform is designed to collect only information relevant to those purposes.' },
  { title: '3. AI and local processing', body: 'Where an AI feature is enabled, the selected startup context may be sent to the configured AI service to generate a response. VentureMind can also use a locally running Ollama model. AI-generated content is guidance and is not used as an automatic legal or financial decision about a person.' },
  { title: '4. Advisor and identity information', body: 'Advisor verification information and consultation documents are restricted to authorised platform administrators and the relevant advisor workflow. Identity documents must never be displayed publicly. Production deployment should add encrypted file storage, defined retention periods, access audits, and a reviewed consent process.' },
  { title: '5. Security and user choices', body: 'The project uses role-based access controls and authenticated API requests. Users should avoid entering unnecessary sensitive information. For this academic demonstration, contact the project owner to request correction or deletion of test data.' },
  { title: '6. Important notice', body: 'This policy is a project-level privacy notice for the local academic demonstration. Before a public or commercial launch, the owner must obtain legal review, publish final controller contact details, define retention periods, and configure applicable privacy, cookie, and data-protection requirements.' },
]

function LegalLayout({ eyebrow, title, intro, sections }: { eyebrow: string; title: string; intro: string; sections: LegalSection[] }) {
  return <div className="-mx-4 -my-8 bg-slate-50 sm:-mx-6 dark:bg-slate-950"><section className="bg-slate-950 px-4 py-16 text-white sm:px-6"><div className="mx-auto max-w-4xl"><Link to="/login" className="text-sm font-semibold text-accent-200 hover:text-white">← Back to sign in</Link><p className="mt-8 text-sm font-bold uppercase tracking-widest text-accent-300">{eyebrow}</p><h1 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">{title}</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-300">{intro}</p><p className="mt-5 text-sm text-slate-400">Last updated: 23 August 2026 · VentureMind AI local academic project</p></div></section><main className="mx-auto max-w-4xl px-4 py-12 sm:px-6"><div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-900"><strong>Academic project notice:</strong> this page explains how the current local VentureMind demonstration is intended to operate. It should be legally reviewed before any public or commercial release.</div><div className="mt-8 space-y-5">{sections.map((section) => <article key={section.title} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-card dark:border-slate-800 dark:bg-slate-900"><h2 className="text-xl font-bold">{section.title}</h2><p className="mt-3 leading-7 text-slate-600 dark:text-slate-300">{section.body}</p></article>)}</div></main></div>
}

export function TermsPage() { return <LegalLayout eyebrow="Legal terms" title="Terms of Service" intro="The conditions for using VentureMind AI and its startup-planning, AI guidance, advisor, and report features." sections={termsSections} /> }

export function PrivacyPage() { return <LegalLayout eyebrow="Privacy and security" title="Privacy Policy" intro="How the VentureMind AI local academic project is intended to process account, startup, advisor, and AI-feature information." sections={privacySections} /> }
