import { useState } from 'react'
import { Button } from '@/components/common/Button'

const templates = { Hiring: ['WE ARE HIRING', 'Join our growing team', 'Apply today'], Launch: ['NOW OPEN', 'Celebrate our opening with us', 'Visit us today'], Offer: ['SPECIAL OFFER', 'Limited-time savings', 'Shop now'] } as const
const themes = { Violet: 'from-violet-700 via-purple-600 to-fuchsia-500', Ocean: 'from-cyan-700 via-blue-600 to-indigo-600', Sunset: 'from-orange-600 via-rose-500 to-fuchsia-600', Forest: 'from-emerald-800 via-teal-600 to-cyan-600' } as const

export function PosterGeneratorPage() {
  const [kind, setKind] = useState<keyof typeof templates>('Hiring'); const [theme, setTheme] = useState<keyof typeof themes>('Violet'); const [business, setBusiness] = useState('My business'); const [location, setLocation] = useState('Jaffna, Sri Lanka'); const [headline, setHeadline] = useState<string>(templates.Hiring[0]); const [body, setBody] = useState<string>(templates.Hiring[1]); const [cta, setCta] = useState<string>(templates.Hiring[2])
  const change = (next: keyof typeof templates) => { setKind(next); setHeadline(templates[next][0]); setBody(templates[next][1]); setCta(templates[next][2]) }
  return <div className="mx-auto max-w-6xl space-y-7"><header><p className="text-sm font-bold uppercase tracking-widest text-brand-600">Poster generator</p><h1 className="mt-2 text-3xl font-bold">Create a launch-ready marketing poster.</h1><p className="mt-2 text-slate-600">Choose a visual theme, edit every message, add your location, then save through the browser print dialog.</p></header><div className="grid gap-7 lg:grid-cols-[0.8fr_1.2fr]"><section className="space-y-4 rounded-2xl border border-slate-200 bg-white p-6 shadow-card"><label className="block text-sm font-semibold">Template<select value={kind} onChange={e=>change(e.target.value as keyof typeof templates)} className="mt-2 w-full rounded-lg border border-slate-300 bg-white p-3 font-normal">{Object.keys(templates).map(x=><option key={x}>{x}</option>)}</select></label><label className="block text-sm font-semibold">Visual theme<select value={theme} onChange={e=>setTheme(e.target.value as keyof typeof themes)} className="mt-2 w-full rounded-lg border border-slate-300 bg-white p-3 font-normal">{Object.keys(themes).map(x=><option key={x}>{x}</option>)}</select></label>{[['Business name',business,setBusiness],['Business location',location,setLocation],['Headline',headline,setHeadline],['Message',body,setBody],['Call to action',cta,setCta]].map(([label,value,setter])=><label key={String(label)} className="block text-sm font-semibold">{String(label)}<input value={String(value)} onChange={e=>(setter as (v:string)=>void)(e.target.value)} className="mt-2 w-full rounded-lg border border-slate-300 bg-white p-3 font-normal"/></label>)}<Button onClick={()=>window.print()}>Print / save as PDF</Button></section><section className="grid min-h-[560px] place-items-center rounded-2xl bg-slate-100 p-5"><article className={`flex aspect-[4/5] w-full max-w-md flex-col justify-between overflow-hidden rounded-3xl bg-gradient-to-br ${themes[theme]} p-9 text-white shadow-2xl`}><div><p className="text-sm font-bold uppercase tracking-[0.25em] text-white/70">{business}</p><p className="mt-2 text-xs font-semibold uppercase tracking-widest text-white/70">{location || 'Your location'}</p><div className="mt-16 h-2 w-16 rounded bg-white/60"/><h2 className="mt-6 text-5xl font-black leading-none">{headline}</h2><p className="mt-6 max-w-xs text-lg leading-7 text-white/90">{body}</p></div><div><p className="inline-block rounded-full bg-white px-5 py-3 text-sm font-bold text-slate-900">{cta}</p><p className="mt-7 text-xs uppercase tracking-widest text-white/70">Designed with VentureMind</p></div></article></section></div></div>
}
