import { Link } from 'react-router-dom'
import { useAuth } from '@/features/auth/AuthContext'

const plans = [
  { name: 'Explorer', price: 'Free', period: 'No card required', description: 'For people exploring a startup opportunity before creating a full workspace.', features: ['Startup Idea Generator', 'Founder learning library', 'Templates, stories, books, and calculators', 'Rapid public idea check'], action: 'Explore free tools', to: '/tools' },
  { name: 'Founder', price: 'LKR 2,500', period: 'per month', description: 'For an individual founder preparing a structured plan and evidence-based next steps.', features: ['Everything in Explorer', 'Startup workspace and saved profile', 'Risk and financial planning', 'PDF business reports', 'AI Advisor context and recommendations'], action: 'Request Founder access', to: '/contact?topic=founder-plan', featured: true },
  { name: 'Team', price: 'LKR 7,500', period: 'per month', description: 'For early teams coordinating planning, documents, advisors, and launch activities.', features: ['Everything in Founder', 'Shared startup workspace', 'Business operations planning', 'Hiring and poster tools', 'Priority support'], action: 'Talk to the team', to: '/contact?topic=team-plan' },
]

export function PricingPage() {
  const { isAuthenticated } = useAuth()
  return <div className="-mx-4 -my-8 sm:-mx-6"><section className="bg-gradient-to-br from-brand-50 via-white to-accent-50 px-4 py-20 text-center dark:from-slate-950 dark:via-slate-950 dark:to-slate-900 sm:px-6"><div className="mx-auto max-w-4xl"><p className="text-sm font-bold uppercase tracking-widest text-brand-600">Straightforward pricing</p><h1 className="mt-4 text-4xl font-bold tracking-tight sm:text-6xl">Choose the support level that fits your startup stage.</h1><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-slate-600 dark:text-slate-300">Start with free learning and planning tools. Upgrade when you need a saved workspace, reports, and guided founder support.</p></div></section>
    <section className="px-4 py-20 sm:px-6"><div className="mx-auto mb-6 max-w-7xl rounded-2xl border border-violet-200 bg-violet-50 px-5 py-4 text-sm leading-6 text-violet-950 dark:border-violet-500/30 dark:bg-violet-950/30 dark:text-violet-100"><strong>Before choosing a paid plan:</strong> create an account and complete your startup profile. This ensures paid workspace guidance is connected to your real business context, not a generic checkout.</div><div className="mx-auto grid max-w-7xl gap-6 lg:grid-cols-3">{plans.map((plan) => { const paidPlan = plan.name !== 'Explorer'; const destination = !paidPlan ? plan.to : isAuthenticated ? '/workspace#startup-profile' : '/register'; const action = !paidPlan ? plan.action : isAuthenticated ? 'Complete startup profile' : 'Start profile setup'; return <article key={plan.name} className={`flex min-h-[500px] flex-col rounded-3xl border p-7 ${plan.featured ? 'border-brand-500 bg-brand-600 text-white shadow-float' : 'border-slate-200 bg-white shadow-card dark:border-slate-800 dark:bg-slate-900'}`}><div className="flex items-start justify-between gap-4"><div><h2 className="text-2xl font-bold">{plan.name}</h2><p className={`mt-3 text-sm leading-6 ${plan.featured ? 'text-brand-100' : 'text-slate-600 dark:text-slate-300'}`}>{plan.description}</p></div>{plan.featured && <span className="rounded-full bg-white/15 px-3 py-1 text-xs font-bold">Recommended</span>}</div><div className="mt-8"><p className="text-4xl font-bold">{plan.price}</p><p className={`mt-1 text-sm ${plan.featured ? 'text-brand-100' : 'text-slate-500'}`}>{plan.period}</p></div><ul className={`mt-7 space-y-3 text-sm ${plan.featured ? 'text-brand-50' : 'text-slate-600 dark:text-slate-300'}`}>{plan.features.map((feature) => <li key={feature} className="flex gap-3"><span aria-hidden="true">✓</span><span>{feature}</span></li>)}</ul><Link className={`mt-auto rounded-xl px-5 py-3 text-center text-sm font-bold ${plan.featured ? 'bg-white text-brand-700 hover:bg-brand-50' : 'bg-brand-600 text-white hover:bg-brand-700'}`} to={destination}>{action}</Link></article> })}</div></section>
    <section className="bg-slate-950 px-4 py-16 text-white sm:px-6"><div className="mx-auto grid max-w-5xl gap-8 md:grid-cols-[1.1fr_0.9fr] md:items-center"><div><p className="text-sm font-bold uppercase tracking-widest text-accent-300">Payment readiness</p><h2 className="mt-3 text-3xl font-bold">Secure payments are prepared for a Sri Lankan gateway.</h2><p className="mt-4 leading-7 text-slate-300">VentureMind will use a hosted payment page, server-side payment verification, and a gateway callback before a subscription is activated. No card data will be stored by VentureMind.</p></div><div className="rounded-2xl border border-white/15 bg-white/10 p-6"><h3 className="text-lg font-bold">Planned payment options</h3><div className="mt-4 space-y-3 text-sm text-slate-200"><p className="rounded-xl bg-white/10 px-4 py-3">PayHere Sri Lanka — hosted checkout</p><p className="rounded-xl bg-white/10 px-4 py-3">Card payments — through the selected gateway</p><p className="rounded-xl bg-white/10 px-4 py-3">Bank transfer — manual confirmation for institutions</p></div><p className="mt-4 text-xs leading-5 text-slate-400">Live checkout is enabled only after a merchant account, secure server credentials, and verified callback URL are configured.</p></div></div></section>
    <section className="bg-slate-100 px-4 py-16 text-center sm:px-6 dark:bg-slate-900/60"><div className="mx-auto max-w-3xl"><h2 className="text-3xl font-bold">Use the free tools today.</h2><p className="mt-4 leading-7 text-slate-600 dark:text-slate-300">You can explore the Idea Generator, learning library, templates, calculators, and startup stories without a payment method.</p><Link className="mt-7 inline-block rounded-lg bg-brand-600 px-5 py-3 text-sm font-bold text-white hover:bg-brand-700" to="/tools">Explore free tools</Link></div></section>
  </div>
}
