import { useState } from 'react'
import { Link } from 'react-router-dom'

const pageContent = {
  competitors: { eyebrow: 'Research resource', title: 'Compare alternatives before claiming an advantage.', intro: 'Use this starter matrix to compare what customers do today, including direct competitors and manual workarounds.', cards: [['Direct competitor', 'Solves the same problem for the same customer. Compare its core workflow, price, and reviews.'], ['Adjacent competitor', 'Solves part of the customer problem from a different angle. Look for gaps in its experience.'], ['Do nothing / manual work', 'Often your strongest competitor. Learn why customers tolerate it and what would make them switch.']] },
  failures: { eyebrow: 'Founder learning', title: 'Common startup failure patterns to test early.', intro: 'These are learning patterns, not verdicts. Use them to decide which assumption deserves your next customer conversation.', cards: [['Problem without urgency', 'People may agree that a problem exists but still not change behaviour or pay to solve it.'], ['Solution before discovery', 'Building too early can hide the fact that the team has not yet understood the customer workflow.'], ['Channel uncertainty', 'A product can be useful but still struggle if there is no repeatable way to reach its users.']] },
  templates: { eyebrow: 'Founder templates', title: 'Simple prompts for your next startup conversation.', intro: 'Copy one of these into your notes and fill it with evidence from interviews or small experiments.', cards: [['Customer interview prompt', 'Tell me about the last time you experienced [problem]. What did you do? What was frustrating? What did it cost you?'], ['Problem hypothesis', 'We believe [customer] struggles with [problem] when [context]. We will know this matters if [evidence].'], ['Experiment plan', 'We will test [assumption] with [audience] by [method]. A useful signal is [measure] within [timeframe].']] },
  glossary: { eyebrow: 'Startup glossary', title: 'Plain-language terms for early-stage founders.', intro: 'A short, practical vocabulary for discussing startup decisions without unnecessary jargon.', cards: [['MVP', 'The smallest version of a product that can test an important assumption with real users.'], ['Problem-solution fit', 'Evidence that a specific customer group recognises a problem and sees value in your proposed approach.'], ['Customer segment', 'A group of people or organisations that share a similar context, need, and purchasing behaviour.'], ['Value proposition', 'The clear reason a target customer should choose your solution over their current alternative.'], ['Unit economics', 'The relationship between the value a customer brings and the cost of acquiring and serving them.'], ['Go-to-market', 'The deliberate plan for reaching, converting, and retaining a target customer group.']] },
  explainable: { eyebrow: 'Our methodology', title: 'What Explainable AI means in VentureMind.', intro: 'A score is useful only when you can inspect the assumptions and factors behind it.', cards: [['Visible factors', 'Each evaluation dimension should identify the positive evidence, missing evidence, and risks affecting the outcome.'], ['Deterministic foundations', 'Core confidence checks use documented weighted factors, rather than random scores.'], ['Human judgement remains central', 'The platform supports structured thinking. It cannot replace customer research, domain expertise, or founder responsibility.']] },
} as const

type ResourceType = keyof typeof pageContent

export function ResourcePage({ type }: { type: ResourceType }) {
  const page = pageContent[type]
  return <div className="-mx-4 -my-8 sm:-mx-6"><section className="bg-gradient-to-br from-brand-50 via-white to-accent-50 px-4 py-20 text-center dark:from-slate-950 dark:via-slate-950 dark:to-slate-900 sm:px-6"><p className="text-sm font-bold uppercase tracking-widest text-brand-600">{page.eyebrow}</p><h1 className="mx-auto mt-4 max-w-4xl text-4xl font-bold tracking-tight sm:text-6xl">{page.title}</h1><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-slate-600 dark:text-slate-300">{page.intro}</p></section><section className="px-4 py-20 sm:px-6"><div className="mx-auto grid max-w-6xl gap-5 md:grid-cols-3">{page.cards.map(([title, description]) => <article key={title} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-card dark:border-slate-800 dark:bg-slate-900"><h2 className="text-xl font-bold">{title}</h2><p className="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-300">{description}</p></article>)}</div><div className="mx-auto mt-12 max-w-3xl rounded-2xl bg-slate-950 p-7 text-center text-white"><h2 className="text-2xl font-bold">Put the learning into practice.</h2><Link className="mt-5 inline-block rounded-lg bg-white px-5 py-3 text-sm font-bold text-brand-700" to="/validate">Try rapid validation</Link></div></section></div>
}

const checklistItems = ['Name the customer group you want to understand.', 'Write the specific problem in the customer’s own words.', 'List the current alternative or workaround.', 'Choose one assumption that could make the idea fail.', 'Plan five customer conversations or a small experiment.', 'Define the observable evidence that would change your mind.']

export function FounderChecklistPage() {
  const [checked, setChecked] = useState<boolean[]>(() => checklistItems.map(() => false))
  const complete = checked.filter(Boolean).length
  return <div className="-mx-4 -my-8 sm:-mx-6"><section className="bg-slate-950 px-4 py-20 text-center text-white sm:px-6"><p className="text-sm font-bold uppercase tracking-widest text-accent-300">Founder checklist</p><h1 className="mt-4 text-4xl font-bold tracking-tight sm:text-6xl">A practical first-pass idea checklist.</h1><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-slate-300">Work through these six steps before you invest deeply in a first version.</p></section><section className="px-4 py-20 sm:px-6"><div className="mx-auto max-w-3xl rounded-2xl border border-slate-200 bg-white p-6 shadow-float dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between gap-4"><h2 className="text-xl font-bold">Your progress</h2><span className="rounded-full bg-brand-50 px-3 py-1 text-sm font-bold text-brand-700 dark:bg-brand-500/10 dark:text-brand-300">{complete}/{checklistItems.length} complete</span></div><div className="mt-6 space-y-3">{checklistItems.map((item, index) => <label key={item} className="flex cursor-pointer items-start gap-3 rounded-xl border border-slate-200 p-4 dark:border-slate-700"><input className="mt-1 h-4 w-4 accent-brand-600" type="checkbox" checked={checked[index]} onChange={() => setChecked((items) => items.map((value, itemIndex) => itemIndex === index ? !value : value))}/><span className={checked[index] ? 'text-slate-400 line-through' : ''}>{item}</span></label>)}</div><p className="mt-6 text-xs text-slate-500">Progress is kept only in this browser session.</p></div></section></div>
}
