import { Link } from 'react-router-dom'

type Story = { company: string; kind: 'Success' | 'Failure'; fact: string; lesson: string; sourceLabel: string; sourceUrl: string }

const stories: Story[] = [
  { company: 'Airbnb', kind: 'Success', fact: 'Airbnb says its founders first hosted three guests on airbeds in San Francisco in 2007, then expanded the concept into a global marketplace.', lesson: 'Start with a small, real interaction that tests whether people will use the behaviour you are proposing.', sourceLabel: 'Airbnb newsroom: About us', sourceUrl: 'https://news.airbnb.com/en-uk/about-us/' },
  { company: 'Slack', kind: 'Success', fact: 'Slack documents that its product originated as an internal communication tool while its team was working on the game Glitch.', lesson: 'Pay attention to tools that solve a recurring problem for your own team; they can reveal a different, more valuable product direction.', sourceLabel: 'Slack: What is Slack?', sourceUrl: 'https://slack.com/intl/de-de/resources/why-use-slack/what-is-slack-and-how-does-it-work' },
  { company: 'Quibi', kind: 'Failure', fact: 'Quibi announced in October 2020 that it was winding down and seeking to sell its content and technology assets.', lesson: 'Treat distribution habits and willingness to pay as testable assumptions before committing heavily to production.', sourceLabel: 'Quibi open letter', sourceUrl: 'https://quibi-hq.medium.com/an-open-letter-from-quibi-8af6b415377f' },
  { company: 'Juicero', kind: 'Failure', fact: 'Juicero announced it was shutting down in 2017 after a connected juice-press business that required proprietary packs.', lesson: 'Test whether the product creates enough customer value beyond the simplest existing alternative.', sourceLabel: 'Axios report on shutdown', sourceUrl: 'https://www.axios.com/2017/12/15/juicero-is-shutting-down-draining-vcs-of-120-million-1513305243' },
]

export function StartupStoriesPage() {
  const successes = stories.filter((story) => story.kind === 'Success')
  const failures = stories.filter((story) => story.kind === 'Failure')
  const renderStory = (story: Story) => <article key={story.company} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-card dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between gap-3"><h3 className="text-xl font-bold">{story.company}</h3><span className={`rounded-full px-3 py-1 text-xs font-bold ${story.kind === 'Success' ? 'bg-emerald-50 text-emerald-700 dark:bg-emerald-500/10 dark:text-emerald-300' : 'bg-amber-50 text-amber-800 dark:bg-amber-500/10 dark:text-amber-200'}`}>{story.kind} story</span></div><p className="mt-4 text-sm leading-6 text-slate-600 dark:text-slate-300">{story.fact}</p><div className="mt-5 rounded-xl bg-brand-50 p-4 dark:bg-brand-500/10"><p className="text-xs font-bold uppercase tracking-widest text-brand-700 dark:text-brand-300">Founder takeaway</p><p className="mt-2 text-sm leading-6 text-slate-700 dark:text-slate-200">{story.lesson}</p></div><a className="mt-5 inline-block text-sm font-bold text-brand-600 hover:underline" href={story.sourceUrl} target="_blank" rel="noreferrer">Read source: {story.sourceLabel} ↗</a></article>
  return <div className="-mx-4 -my-8 sm:-mx-6"><section className="bg-slate-950 px-4 py-20 text-center text-white sm:px-6"><p className="text-sm font-bold uppercase tracking-widest text-accent-300">Verified startup stories</p><h1 className="mt-4 text-4xl font-bold tracking-tight sm:text-6xl">Learn from outcomes, not myths.</h1><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-slate-300">Short documented stories with source links and careful, practical lessons for early-stage founders.</p></section><section className="px-4 py-20 sm:px-6"><div className="mx-auto max-w-7xl"><div><p className="text-sm font-bold uppercase tracking-widest text-brand-600">Success stories</p><h2 className="mt-3 text-3xl font-bold">What an early signal can reveal.</h2></div><div className="mt-8 grid gap-5 md:grid-cols-2">{successes.map(renderStory)}</div><div id="failures" className="mt-16"><p className="text-sm font-bold uppercase tracking-widest text-brand-600">Failure stories</p><h2 className="mt-3 text-3xl font-bold">What an assumption can hide.</h2></div><div className="mt-8 grid gap-5 md:grid-cols-2">{failures.map(renderStory)}</div><div className="mx-auto mt-14 max-w-3xl rounded-2xl bg-brand-50 p-7 text-center dark:bg-brand-500/10"><h2 className="text-2xl font-bold">Use a story to frame your next test.</h2><p className="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-300">A story is context, not proof that your idea will succeed or fail. Test your own customer, market, and execution assumptions.</p><Link className="mt-5 inline-block rounded-lg bg-brand-600 px-5 py-3 text-sm font-bold text-white hover:bg-brand-700" to="/validate">Try rapid validation</Link></div></div></section></div>
}
