import { Link } from 'react-router-dom'

const books = [
  { title: 'The Lean Startup', author: 'Eric Ries', focus: 'Experimentation and validated learning', description: 'A guide to using small experiments, feedback, and iteration to reduce uncertainty while building a startup.', link: 'https://theleanstartup.com/book', source: 'Official book site', pair: 'Use with: Problem Hypothesis and Experiment Plan templates' },
  { title: 'The Mom Test', author: 'Rob Fitzpatrick', focus: 'Customer discovery interviews', description: 'A practical guide to asking customers useful questions without leading them toward the answer you want.', link: 'https://www.momtestbook.com/', source: 'Official book site', pair: 'Use with: Validation Interview template' },
  { title: 'Venture Deals', author: 'Brad Feld and Jason Mendelson', focus: 'Fundraising and venture capital', description: 'An introduction to the venture-capital deal process, useful when you need to understand funding discussions and terms.', link: 'https://venturedeals.com/the-book/', source: 'Official book site', pair: 'Use with: Funding and Equity Dilution calculators' },
  { title: 'INSPIRED', author: 'Marty Cagan', focus: 'Product discovery and product teams', description: 'A guide to creating technology products customers value, with emphasis on discovery, delivery, and product practice.', link: 'https://www.svpg.com/books/inspired-how-to-create-tech-products-customers-love-2nd-edition/', source: 'SVPG book page', pair: 'Use with: Customer Persona and Competitor Analysis templates' },
]

export function StartupBooksPage() {
  return <div className="-mx-4 -my-8 sm:-mx-6"><section className="bg-gradient-to-br from-brand-50 via-white to-accent-50 px-4 py-20 text-center dark:from-slate-950 dark:via-slate-950 dark:to-slate-900 sm:px-6"><p className="text-sm font-bold uppercase tracking-widest text-brand-600">Founder reading library</p><h1 className="mt-4 text-4xl font-bold tracking-tight sm:text-6xl">Books for the questions founders face first.</h1><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-slate-600 dark:text-slate-300">A curated set of legitimate publisher and author links. Choose a topic, then pair the reading with a practical VentureMind tool.</p></section><section className="px-4 py-20 sm:px-6"><div className="mx-auto grid max-w-6xl gap-5 md:grid-cols-2">{books.map((book, index) => <article key={book.title} className="flex min-h-[320px] gap-5 rounded-2xl border border-slate-200 bg-white p-6 shadow-card dark:border-slate-800 dark:bg-slate-900"><div className="grid h-14 w-12 shrink-0 place-items-center rounded-md bg-brand-600 text-lg font-bold text-white shadow-lg shadow-brand-600/25">{index + 1}</div><div className="flex flex-col"><p className="text-xs font-bold uppercase tracking-widest text-brand-600">{book.focus}</p><h2 className="mt-2 text-2xl font-bold">{book.title}</h2><p className="mt-1 text-sm font-medium text-slate-500 dark:text-slate-400">{book.author}</p><p className="mt-4 text-sm leading-6 text-slate-600 dark:text-slate-300">{book.description}</p><p className="mt-4 text-xs font-semibold text-slate-500 dark:text-slate-400">{book.pair}</p><a className="mt-auto pt-5 text-sm font-bold text-brand-600 hover:underline" href={book.link} target="_blank" rel="noreferrer">Open {book.source} ↗</a></div></article>)}</div><div className="mx-auto mt-14 max-w-3xl rounded-2xl bg-slate-950 p-7 text-center text-white"><h2 className="text-2xl font-bold">Read, then test one assumption.</h2><p className="mt-3 text-sm leading-6 text-slate-300">Books can improve your questions; customer evidence is still what improves your decision.</p><Link className="mt-5 inline-block rounded-lg bg-white px-5 py-3 text-sm font-bold text-brand-700 hover:bg-brand-50" to="/templates">Open founder templates</Link></div></section></div>
}
