import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'

type Template = { id: string; title: string; description: string; fields: { key: string; label: string; placeholder: string }[] }

const templates: Template[] = [
  { id: 'persona', title: 'Customer Persona', description: 'Clarify who you are building for, their context, goals, and blockers.', fields: [{ key: 'segment', label: 'Customer segment', placeholder: 'Independent cafe owners in Colombo' }, { key: 'goal', label: 'Primary goal', placeholder: 'Reduce time spent ordering stock' }, { key: 'pain', label: 'Primary pain point', placeholder: 'Stock decisions rely on guesswork' }, { key: 'alternative', label: 'Current alternative', placeholder: 'Spreadsheets and supplier calls' }] },
  { id: 'interview', title: 'Validation Interview', description: 'Prepare non-leading questions for a customer discovery conversation.', fields: [{ key: 'customer', label: 'Who will you interview?', placeholder: 'Owners of small retail shops' }, { key: 'problem', label: 'Problem to investigate', placeholder: 'Difficulty forecasting demand' }, { key: 'context', label: 'Situation to explore', placeholder: 'The last time they ordered stock' }] },
  { id: 'competitor', title: 'Competitor Analysis', description: 'Compare an alternative on positioning, strengths, and gaps.', fields: [{ key: 'competitor', label: 'Competitor or alternative', placeholder: 'Manual spreadsheet workflow' }, { key: 'customer', label: 'Shared customer', placeholder: 'Independent retailers' }, { key: 'strength', label: 'What it does well', placeholder: 'Familiar and inexpensive' }, { key: 'gap', label: 'Gap to investigate', placeholder: 'No demand prediction or collaboration' }] },
  { id: 'hypothesis', title: 'Problem Hypothesis', description: 'Turn a broad startup thought into a testable statement.', fields: [{ key: 'customer', label: 'Customer', placeholder: 'Independent cafe owners' }, { key: 'problem', label: 'Problem', placeholder: 'They waste money through inaccurate stock orders' }, { key: 'context', label: 'Context', placeholder: 'When planning weekly purchases' }, { key: 'evidence', label: 'Evidence you need', placeholder: 'Five owners describe the issue as costly and urgent' }] },
  { id: 'experiment', title: 'Experiment Plan', description: 'Define a smallest useful test before building a full product.', fields: [{ key: 'assumption', label: 'Assumption to test', placeholder: 'Owners will share sales data for better forecasts' }, { key: 'audience', label: 'Audience', placeholder: 'Five independent cafes' }, { key: 'method', label: 'Test method', placeholder: 'A manual weekly forecast service' }, { key: 'signal', label: 'Success signal', placeholder: 'Three cafes use the forecast for four weeks' }] },
  { id: 'pitch', title: 'One-Minute Pitch', description: 'Create a concise explanation of the problem, customer, and value.', fields: [{ key: 'company', label: 'Startup name', placeholder: 'ClarityFlow' }, { key: 'customer', label: 'Target customer', placeholder: 'Independent cafes' }, { key: 'problem', label: 'Problem', placeholder: 'Uncertain stock decisions create waste' }, { key: 'solution', label: 'Solution', placeholder: 'A simple demand-planning workflow' }] },
]

function renderDraft(template: Template, values: Record<string, string>) {
  const value = (key: string) => values[key]?.trim() || `[${template.fields.find((field) => field.key === key)?.label.toLowerCase() ?? key}]`
  if (template.id === 'persona') return `CUSTOMER PERSONA\n\nSegment: ${value('segment')}\nGoal: ${value('goal')}\nPain point: ${value('pain')}\nCurrent alternative: ${value('alternative')}\n\nNext question: What would make this customer change from their current alternative?`
  if (template.id === 'interview') return `VALIDATION INTERVIEW\n\nInterviewee: ${value('customer')}\nProblem to investigate: ${value('problem')}\nContext: ${value('context')}\n\nQuestions:\n1. Tell me about the last time ${value('context').toLowerCase()}.\n2. What did you do first?\n3. What was difficult or costly about it?\n4. What have you already tried?\n5. How do you decide whether a different approach is worthwhile?`
  if (template.id === 'competitor') return `COMPETITOR ANALYSIS\n\nAlternative: ${value('competitor')}\nShared customer: ${value('customer')}\nStrength: ${value('strength')}\nGap to investigate: ${value('gap')}\n\nNext question: Is the gap important enough for the customer to switch or pay?`
  if (template.id === 'hypothesis') return `PROBLEM HYPOTHESIS\n\nWe believe ${value('customer')} struggles with ${value('problem')} when ${value('context')}.\n\nWe will consider this important if: ${value('evidence')}.`
  if (template.id === 'experiment') return `EXPERIMENT PLAN\n\nAssumption: ${value('assumption')}\nAudience: ${value('audience')}\nMethod: ${value('method')}\nSuccess signal: ${value('signal')}\n\nDecision rule: Continue only if the success signal is observed with real users.`
  return `ONE-MINUTE PITCH\n\n${value('company')} helps ${value('customer')} who face ${value('problem')}.\n\nOur approach: ${value('solution')}.\n\nNext step: validate whether this customer sees the problem as urgent enough to change behaviour.`
}

export function TemplatesPage() {
  const [selectedId, setSelectedId] = useState(templates[0].id)
  const [values, setValues] = useState<Record<string, string>>({})
  const [copied, setCopied] = useState(false)
  const selected = templates.find((template) => template.id === selectedId) ?? templates[0]
  const draft = useMemo(() => renderDraft(selected, values), [selected, values])
  const choose = (id: string) => { setSelectedId(id); setValues({}); setCopied(false) }
  const copyDraft = async () => { try { await navigator.clipboard.writeText(draft); setCopied(true) } catch { setCopied(false) } }

  return <div className="-mx-4 -my-8 sm:-mx-6"><section className="bg-gradient-to-br from-brand-50 via-white to-accent-50 px-4 py-20 text-center dark:from-slate-950 dark:via-slate-950 dark:to-slate-900 sm:px-6"><p className="text-sm font-bold uppercase tracking-widest text-brand-600">Editable founder templates</p><h1 className="mt-4 text-4xl font-bold tracking-tight sm:text-6xl">Structure your next founder conversation.</h1><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-slate-600 dark:text-slate-300">Fill a short template and copy a structured draft into your own notes. Nothing is stored on VentureMind.</p></section><section className="px-4 py-16 sm:px-6"><div className="mx-auto max-w-7xl"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{templates.map((template) => <button key={template.id} onClick={() => choose(template.id)} className={`rounded-xl border p-4 text-left ${selected.id === template.id ? 'border-brand-500 bg-brand-50 dark:bg-brand-500/10' : 'border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900'}`}><p className="font-bold">{template.title}</p><p className="mt-1 text-xs leading-5 text-slate-600 dark:text-slate-300">{template.description}</p></button>)}</div><div className="mt-9 grid gap-7 lg:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-float dark:border-slate-800 dark:bg-slate-900"><p className="text-sm font-bold uppercase tracking-widest text-brand-600">{selected.title}</p><h2 className="mt-2 text-2xl font-bold">Fill your starting points</h2><div className="mt-6 space-y-4">{selected.fields.map((field) => <label key={field.key} className="block text-sm font-semibold">{field.label}<input value={values[field.key] ?? ''} onChange={(event) => setValues((current) => ({ ...current, [field.key]: event.target.value }))} className="mt-2 w-full rounded-lg border border-slate-300 bg-transparent p-3 font-normal dark:border-slate-700" placeholder={field.placeholder}/></label>)}</div></div><aside className="rounded-2xl bg-slate-950 p-6 text-white"><p className="text-sm font-bold uppercase tracking-widest text-accent-300">Your draft</p><pre className="mt-5 whitespace-pre-wrap font-sans text-sm leading-6 text-slate-200">{draft}</pre><button className="mt-7 rounded-lg bg-white px-5 py-3 text-sm font-bold text-brand-700 hover:bg-brand-50" onClick={() => void copyDraft()}>{copied ? 'Copied to clipboard' : 'Copy draft'}</button><Link className="ml-4 text-sm font-bold text-accent-300 hover:underline" to="/register">Start a startup plan</Link></aside></div></div></section></div>
}
