import { useState } from 'react'
import { useParams } from 'react-router-dom'
import { apiClient } from '@/api/client'
type Message = { role: 'user' | 'assistant'; content: string }
export function ChatPage() {
  const { projectId } = useParams(); const [messages, setMessages] = useState<Message[]>([]); const [input, setInput] = useState(''); const [conversationId, setConversationId] = useState<string>(); const [loading, setLoading] = useState(false)
  const send = async () => { if (!input.trim() || !projectId) return; const message = input; setInput(''); setMessages((items) => [...items, { role: 'user', content: message }]); setLoading(true); try { const { data } = await apiClient.post(`/projects/${projectId}/chat`, { message, conversation_id: conversationId }); setConversationId(data.data.conversation_id); setMessages((items) => [...items, { role: 'assistant', content: data.data.response }]) } finally { setLoading(false) } }
  return <div className="mx-auto flex h-[70vh] max-w-4xl flex-col rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h1 className="text-xl font-bold">VentureMind AI Assistant</h1><div className="mt-5 flex-1 space-y-3 overflow-y-auto">{messages.length === 0 && <p className="text-slate-500">Ask about your startup idea, evaluation scores, risks, or next steps.</p>}{messages.map((item, index) => <div key={index} className={`max-w-[85%] rounded-xl p-3 text-sm ${item.role === 'user' ? 'ml-auto bg-brand-600 text-white' : 'bg-slate-100 dark:bg-slate-800'}`}>{item.content}</div>)}</div><div className="mt-4 flex gap-2"><input className="flex-1 rounded-lg border border-slate-300 bg-transparent px-3 py-2 dark:border-slate-700" value={input} onChange={(event) => setInput(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') void send() }} placeholder="Ask a question..."/><button className="rounded-lg bg-brand-600 px-4 py-2 text-sm font-bold text-white disabled:opacity-60" disabled={loading} onClick={() => void send()}>{loading ? 'Thinking...' : 'Send'}</button></div></div>
}
