"""Expand the VentureMind report into a thesis-length, citation-led document.

The text deliberately distinguishes implemented features from future work and does
not invent participant-study results.  It is intended as a strong editable draft
for the student's final supervisor review.
"""
from pathlib import Path
from docx import Document
from docx.shared import Pt

ROOT = Path(__file__).resolve().parents[1]
PATH = ROOT / "output" / "reports" / "VentureMind_AI_Final_Project_Report.docx"


def add_after(anchor, text):
    """Insert a normal paragraph immediately after an existing paragraph."""
    doc = anchor.part.document
    p = doc.add_paragraph(text)
    p.style = doc.styles["Normal"]
    p.paragraph_format.space_after = Pt(7)
    anchor._p.addnext(p._p)
    return p


def anchor_after_section(document, heading):
    paragraphs = document.paragraphs
    start = next(i for i, p in enumerate(paragraphs) if p.text.strip() == heading)
    end = next((i for i in range(start + 1, len(paragraphs)) if paragraphs[i].style.name.startswith("Heading")), len(paragraphs))
    return paragraphs[end - 1]


sections = {
"1.1 Background": [
"New ventures make decisions under severe uncertainty: founders often have incomplete knowledge of customers, limited capital, few operating records and little time to compare alternatives. Digital business-planning tools can reduce this friction, but many provide isolated calculators or generic idea suggestions rather than a traceable journey from a startup profile to a risk explanation, action plan and operational follow-up. VentureMind AI was conceived as an integrated decision-support platform for this gap. Its purpose is not to certify that an idea will succeed. Instead, it helps a founder document assumptions, see uncertainty explicitly and decide what evidence to collect next.",
"The project is particularly relevant to early-stage founders in Sri Lanka, where business registration, local permissions, informal market research and resource constraints commonly shape the first months of a venture. A founder may require help with a food business in Jaffna, a small service firm in Colombo or a digital product aimed at a wider market; the platform therefore keeps country and location as explicit profile data instead of assuming a generic global market. The design links planning to practical activities such as customer interviews, a simple budget, legal checks and a meeting with a human advisor. This approach is consistent with the Lean Startup view that learning is gained through measurable experiments rather than elaborate assumptions (Ries, 2011)."
],
"1.2 Problem Statement": [
"Existing founder-support websites frequently separate idea generation, business plans, legal information, hiring templates and advisor directories into unrelated pages. This forces the user to repeat information and makes it difficult to understand why a score or recommendation has been generated. A startup founder may receive a number labelled 'confidence' without knowing which missing information, market assumptions or operational constraints led to that number. Such opaque outputs are unsuitable for a university project that claims to use artificial intelligence responsibly.",
"The practical problem addressed by this dissertation is therefore twofold. First, founders need a single workspace that guides them through a clear sequence: describe the venture, evaluate the available evidence, plan finances and requirements, take action and review progress. Secondly, platform administrators and human advisors need controlled workflows for verification, booking, messages, document requests and monitoring. The system must meet these needs without claiming to replace lawyers, accountants, investors or market research. It must also work locally before expensive external services such as Maps, email, payment and generative AI are enabled."
],
"1.3 Aim and Objectives": [
"The aim is to design and implement a locally deployable, AI-assisted startup lifecycle management platform that gives founders understandable, evidence-based planning support. The aim is achieved through a set of linked objectives: capture a structured startup profile; calculate repeatable risk and confidence indicators; present the reasoning behind each indicator; generate practical financial, requirement and legal guidance; support authenticated roles; and preserve relevant records in a relational database. The implementation additionally provides a pathway for human legal advisors and business mentors, recognising that some questions require professional judgement rather than automated text.",
"The objectives are deliberately measurable at the feature level. For example, a founder should be able to save a project and see it after refresh; a risk output should list positive evidence, gaps and a next action; an administrator should be able to manage accounts and review advisor applications; and an advisor should be able to receive and respond to booking requests. These objectives provide acceptance criteria for testing. They also limit scope: VentureMind AI is not an autonomous business-registration service, a legal practice, an employment payroll system or a live social-media publisher in its current local deployment."
],
"1.4 Scope": [
"The implemented scope covers the early and pre-operational lifecycle of a startup. The founder experience includes public discovery pages, authentication, rapid validation, a startup workspace, explainable risk analysis, investment planning, business requirements, Sri Lanka-oriented legal guidance, reports, an AI advisor interface, hiring and operations planning. The administrative experience includes role-aware platform metrics, user management, feedback review, announcement and content management, audit-oriented actions, and advisor verification. The advisor experience includes an application route, profile/directory visibility after approval, availability slots, booking management, messages and protected document-request workflows.",
"Several integrations are intentionally treated as configurable boundaries. Gemini is optional and a structured deterministic response is shown if an AI key is not configured. Google Places can be connected for real competitor listings only when the organisation owns a valid key and billing configuration. Email, video meetings and payment providers are designed as future integration points; local demonstration flows should never be described as live financial or legal services. This scope is technically realistic for a final-year development project and makes the distinction between a working prototype and production deployment clear."
],
"2.1 Startup Validation and Lean Experimentation": [
"Ries (2011) argues that new ventures should manage uncertainty through a build-measure-learn cycle. Rather than asking a founder to produce a perfect prediction, VentureMind AI converts a broad idea into testable assumptions: who has the problem, how often it occurs, what alternative is used today, whether customers will pay, and what smallest version of a solution can be tried. The startup workspace therefore promotes customer interviews, narrow customer segments, pricing experiments and minimum viable product steps. These recommendations do not prove demand; they organise the next learning activity.",
"The Business Model Canvas is another useful foundation because it connects value proposition, customer segments, channels, revenue streams, costs, resources, activities and partners in one visual model (Osterwalder and Pigneur, 2010). VentureMind AI retains this connected perspective when producing planning guidance. A score should not be interpreted separately from the founder's claimed customer, business model or budget. For example, a high technical feasibility assessment with no evidence of willingness to pay should still indicate material customer and market uncertainty. This cross-field relationship is a key reason for storing the startup profile in normalised data structures rather than processing one unstructured text area only."
],
"2.2 Explainable Decision Support": [
"Explainability is important when software influences a founder's next decision. Molnar (2022) distinguishes between predictive performance and the ability of a person to understand why a model arrived at an output. In a startup setting, the latter is essential because an unexplained score can create unwarranted confidence or discourage a promising idea without a useful route forward. VentureMind AI therefore represents each risk dimension with a score, an explanation, supporting or missing evidence and an improvement action. The founder is shown not simply that market risk is high, but that the target segment, local demand evidence or competitor differentiation is insufficiently specified.",
"The present implementation uses transparent weighted rules rather than claiming a trained success-prediction model. This is an intentional methodological choice. A machine-learning model would require a representative longitudinal dataset of startups, consistent labels for success, careful bias testing and independent validation. Without those assets, a complex model could appear intelligent while being less defensible than documented business rules. The architecture is nevertheless ML-ready: feature extraction, embeddings, NLP and SHAP-compatible interfaces are separated from API and presentation layers. Future research may compare the current transparent baseline with a carefully evaluated learning model."
],
"2.3 Relevant Technology Choices": [
"React with TypeScript supports reusable, type-aware client components and a single-page experience, while Vite provides a fast local development environment. React Router separates public, founder, administrator and advisor routes. React Hook Form is used for structured data capture and validation, Axios manages API communication, Tailwind CSS supplies a consistent design system, and Recharts supports readable visualisations. These choices align with the objective of a responsive demonstration interface without coupling page components directly to database code.",
"FastAPI was selected for the server because it supports Python type hints, automatic request validation through Pydantic and interactive OpenAPI/Swagger documentation (FastAPI, 2026; Pydantic, 2026). SQLAlchemy provides an object-relational layer and Alembic controls schema evolution. MySQL provides durable relational persistence for identities, projects, evaluations, operational records and advisory workflows. This combination also supports separation of concerns: route handlers validate transport data, services implement business rules, repositories/models persist state, and the frontend remains a consumer of stable REST contracts. The design reduces the risk that a change to one dashboard directly breaks another role's workflow."
],
"3.1 Development Methodology": [
"An iterative, risk-driven development approach was used. Each increment focused on an end-to-end vertical slice rather than building all screens before testing persistence. Initial increments established the folder structure, FastAPI architecture, React application, MySQL schema and JWT authentication. Later increments added founder profiles, risk analysis, financial planning, reports, operations, administration and the advisor workflow. This approach is compatible with agile principles because requirements were refined after observing the behaviour of the existing system and discussing its usability during development (Schwaber and Sutherland, 2020).",
"The workflow also follows design science thinking: identify a practical problem, construct an artefact, demonstrate it in a relevant setting and evaluate it against criteria. The artefact is the VentureMind AI platform; its evaluation criteria include persistence, role isolation, traceability of scores, task completion and clarity of next steps. The process did not treat interface mock-ups as the final output. Screens were connected progressively to APIs and database records where feasible. When a live external dependency was unavailable, the interface was designed to disclose the condition and provide a safe fallback rather than fabricate a result."
],
"3.2 Research and Evaluation Approach": [
"This project is primarily an applied software-engineering artefact with a planned mixed-method evaluation. Functional verification establishes whether the system can complete defined role-based workflows. A future usability evaluation should recruit founders or entrepreneurship students, ask them to complete realistic tasks and gather both completion observations and perceived clarity ratings. Semi-structured follow-up questions can explore whether users understood the reasons behind a risk output and whether the recommended next action was practical. Creswell and Creswell (2018) note that mixed methods can combine measurable patterns with explanatory participant feedback; this is suitable for evaluating a decision-support interface.",
"No fabricated study results are included in this report. Before collecting participant data, the student should prepare consent information, explain that the prototype does not provide financial or legal advice, remove personally identifying information from analysis and obtain the required university approval. Suggested measures are task-completion rate, time to find the next action, System Usability Scale score, errors per workflow and qualitative themes. Results should be reported with participant count, method, limitations and raw evidence. This is stronger academically than presenting unsourced percentages from a prototype demonstration."
]
,
"4.1 Actors": [
"The guest actor is deliberately restricted to low-risk discovery activities: viewing the landing content, exploring learning resources, using limited rapid validation and choosing to register. A founder is the primary business user. A founder owns startup projects, completes a structured profile, views planning outputs, generates reports, submits feedback and can request support from approved human advisors. The separation of guest and founder reduces accidental exposure of project-specific data and gives a clear conversion path without hiding the purpose of the platform.",
"The administrator is a governance actor rather than a founder with additional menu items. The administrator monitors platform accounts, roles, feedback, announcements, content records, audit history and advisor verification. A legal advisor or business mentor has a separate professional workflow: manage their own profile and availability, review incoming booking requests, exchange guidance with the founder and request only the documents necessary for an appointment. Other future roles, such as investor, job applicant and employee, are represented as extensible roles but must receive dedicated least-privilege permissions before they are considered production-ready. This role model follows the principle of least privilege recommended by OWASP (2021)."
],
"4.2 Functional Requirements": [
"Functional requirements were specified as observable system behaviours. In the identity area, the platform shall register and authenticate users, issue and refresh JSON Web Tokens, restrict protected endpoints and route users to a role-appropriate view. In the startup-planning area, it shall allow founders to create and edit a profile containing business identity, category, customer, location, investment, experience, team and timeline fields. It shall retain these fields in MySQL so that a refresh does not discard work. The system shall then derive an explainable evaluation and store it against the related project rather than displaying anonymous sample values.",
"In the lifecycle area, the system shall create a financial plan from founder assumptions, present a requirements checklist, provide legal checklist information, enable report generation and record operations such as people, tasks, attendance, leave and announcements. In the advisory area, it shall show only approved advisor profiles to founders; accept consultation requests; enable advisors to accept, decline, reschedule or complete bookings; record messages; request documents; and surface status changes to the founder. In the governance area, it shall support account review, role changes where authorised, archiving instead of unsafe removal, advisor-verification review and activity monitoring. Each requirement is backed by a page, API contract or database entity, making it testable."
],
"4.3 Non-functional Requirements": [
"Usability is a central non-functional requirement because founders may be unfamiliar with financial, legal or AI terminology. Screens should use a clear page title, one primary action, accessible labels, meaningful empty states and a visible next step. Multi-step profile collection must save progress and should block downstream tasks only when they require missing prerequisite information. Responsive layouts are required for laptop demonstrations and smaller screens, although the detailed workspace is optimised for desktop use. The interface should distinguish user-entered information, generated suggestions and sample data so that users do not mistake illustrative values for their own records.",
"Reliability and maintainability are addressed through modular frontend components, typed backend schemas, central error handling, logging and Alembic migrations. A migration is part of the release process: changing a SQLAlchemy model without applying the related revision can produce runtime 'unknown column' errors, so the documented local command is python -m alembic upgrade head. Security requirements include hashed passwords, server-side role checks, validation of input data, secret configuration in environment files and protected handling of advisor identity evidence. Performance targets for a local prototype are modest: normal form pages and saved project summaries should respond within a few seconds in a local environment, while external AI or Places requests may require an explicit loading state and timeout."
],
"5.1 High-Level Architecture": [
"The architecture is layered so that responsibilities can be understood and changed independently. The React client is responsible for interaction, form-level validation, route navigation, charts and presentation. It communicates with versioned REST endpoints rather than accessing MySQL directly. FastAPI receives requests, validates payloads using Pydantic schemas, authenticates tokens, checks roles and delegates business work to services. Domain services hold deterministic scoring, advisor booking, report generation, document-protection and notification logic. SQLAlchemy models and repositories persist the result in MySQL through a controlled session boundary.",
"This separation supports SOLID-oriented design. For example, an AdvisorBookingService can be tested with a repository abstraction without rendering the entire dashboard, while a frontend AdvisorCard can be reused without knowing database table names. Optional integrations sit at the outer boundary: a Gemini-compatible provider can generate enriched text, Google Places can retrieve live listings and an email provider can send resets or reminders. The core platform continues to function with disclosed local fallbacks when such providers are absent. Diagram 1 is intended to be redrawn using the prompt supplied in Appendix D for a polished final submission figure."
],
"5.2 Founder Workflow": [
"The founder workflow begins with orientation rather than immediate scoring. A guest can understand the platform and use a limited validation route; after registration, the founder creates a named project. The profile wizard captures business identity, problem, customer, location, budget and operational context. This context becomes the common source for all later modules. The platform should present the next incomplete prerequisite prominently: for example, complete the profile before generating a full evaluation, then examine evidence gaps before moving to finance or legal preparation. This prevents the workspace from appearing as a collection of unrelated cards.",
"Once the profile is sufficiently complete, the risk engine calculates dimensions such as customer, market, financial, legal and scalability risk. Each output provides a score out of 100, a plain-language explanation and a specific action. The founder may then generate a financial plan, work through requirements, review legal guidance, create a report and request a mentor or legal consultation. Their dashboard should summarise current project status, pending advisor messages and next actions, not merely display dashboard decoration. Diagram 2 represents this lifecycle as a user-centred activity flow."
],
"5.3 Database Design": [
"The database is normalised around stable ownership relationships. Users store identity, credentials, role, activation and archival state. Projects and startup profiles belong to a founder. Evaluations and evaluation scores belong to a project, allowing repeated evaluations rather than overwriting history. Financial plans, lifecycle milestones, risk assessments, reports and operational records reference the project or organisation that owns them. This design supports a future multi-project founder and avoids duplicating the same business identity across different modules.",
"Human-advisor workflows use separate entities for advisor profiles, availability slots, booking requests, messages, document requests, shared documents, reminders and payment records. Separation is important because a booking can have many messages and requested documents, while an advisor can have many slots and bookings. Sensitive artefacts must not be stored as public paths. The current architecture provides encrypted private-storage intent and restricted access rules; a production deployment should use managed object storage, encryption keys outside the database and lifecycle deletion policies. MySQL tables should use InnoDB to enforce foreign keys and transactions; MyISAM is unsuitable for workflow data that depends on relational consistency."
],
"5.4 API Design": [
"REST endpoints are grouped by resource and protected by dependency-based authentication. Typical endpoints include /api/v1/auth for registration, login, refresh and password reset; /api/v1/projects and /api/v1/startup-profiles for founder-owned data; evaluation, report and operations endpoints for related business functions; /api/v1/admin for governance; and /api/v1/human-advisors for directory, slots, bookings, messages and documents. The exact endpoint list is exposed by FastAPI Swagger at /docs when the backend is running locally. This provides a useful demonstration of request/response contracts to a supervisor.",
"The API follows consistent response and error principles: invalid requests should yield a 422 validation response, unauthenticated calls 401, unauthorised role access 403, missing records 404 and unique-data conflicts 409 where relevant. The frontend should turn server errors into clear user messages rather than claiming an email is already registered when the real issue is an unavailable database. A request ID and structured server log improve diagnosis during development. Rate limiting, monitoring and production CORS policy are future deployment concerns, but the API boundaries already make these additions possible."
],
"5.5 Explainable Evaluation Design": [
"The evaluation engine is deliberately deterministic. Each risk dimension starts from a documented baseline, then applies defined adjustments based on available profile evidence. A vague customer segment or absent demand-validation plan raises customer and market uncertainty; a stated budget, revenue approach or regulatory plan can reduce specific uncertainty. The final score is bounded between 0 and 100 and translated into a priority band. Crucially, the engine returns the individual factors used so that the UI can display positive evidence, negative evidence and an improvement suggestion. Scores are therefore reproducible for identical input.",
"This design is more appropriate than random values or unexplained LLM text. Generative AI may assist with language generation, keyword extraction or contextual suggestions, but the scoring rationale remains inspectable. If a future model is trained, model governance should include the training-data origin, feature definitions, version number, performance metrics, bias analysis and SHAP explanations. SHAP is a useful technique for attributing feature influence in compatible predictive models, but its use would not by itself make a model trustworthy; user-facing explanations must still be accurate, understandable and calibrated (Lundberg and Lee, 2017; Molnar, 2022)."
]
,
"6.1 Founder Experience": [
"The founder interface is designed as a guided workspace rather than a long navigation menu. The dashboard should identify the current project, display a concise summary of saved evidence and show the next recommended action. Large lifecycle checklists are therefore broken into focused cards or numbered steps. The founder can begin with business identity, then customer and location information, then financial assumptions, and finally submit for a full analysis. Saving a draft is a first-class action because early-stage founders may not have every fact available in one session.",
"After analysis, the results page turns numeric outputs into decisions. Visual charts support comparison across dimensions, while a detailed evidence panel explains why a score exists. The user can continue to a financial forecast, requirement checklist and legal guidance without re-entering base information. Report filenames should use a project name and readable date rather than an opaque UUID. Where data is absent, the page should explain how to create the first project or analysis. This behaviour is preferable to a blank screen or hard-coded demonstration content because it maintains user trust and enables a clear end-to-end viva demonstration."
],
"6.2 Administration and Governance": [
"The administration dashboard has a distinct purpose from the founder dashboard. It must not contain founder actions such as 'evaluate my idea'. Instead, it provides platform-level indicators: registered and active users, projects, completed evaluations, report volumes, open feedback, AI usage and governance alerts. Administrators can search and filter accounts, verify email state, change allowed roles, suspend or reactivate accounts and archive accounts that should no longer appear in routine lists. Important records should not be hard-deleted, because projects, bookings and audit trails may depend on them.",
"Governance includes advisor verification. In the current intended workflow, an applicant creates a normal account and submits an advisor application with professional information and protected supporting evidence. An administrator reviews the application, validates the qualification or registration reference, decides whether the advisor profile is visible and assigns the advisor role only after approval. The administrator can later edit the profile, temporarily suspend it for a complaint or expired qualification and view associated bookings. Every high-impact action should be captured in an audit log with actor, timestamp, target, action and outcome. This supports accountability and offers a practical explanation of role-based access control during assessment."
],
"6.3 Advisor and Appointment Management": [
"The human-advisor module corrects a common weakness of generic AI startup tools: some questions require a qualified person. Founders browse only approved legal advisors and business mentors, view specialisation, languages, availability and consultation fee, choose a slot and submit a request. The request becomes a controlled workflow rather than an untracked contact form. Its states include pending, accepted, declined, rescheduled, cancelled and completed. A change of state should create an in-app notification for the founder and advisor; an email or calendar notification may later be sent through an external provider.",
"Advisors manage availability slots and booking details from their own dashboard. They may add a meeting link for online sessions, explain a reschedule decision, send a follow-up message or ask for particular documents. The founder sees requests, messages and document status in their dashboard. Sensitive items such as NIC/passport copies, business registration certificates, TIN documents, lease agreements, business plans and forecasts must be requested only when necessary. They require access control, encrypted storage, retention limits and an explicit privacy notice. The local implementation demonstrates the workflow, whereas real payment capture and secure cloud document storage must be completed before public deployment."
],
"6.4 External Integration Boundaries": [
"A professional system clearly distinguishes implemented behaviour from optional providers. Gemini can enhance the AI Business Advisor by using the founder's saved context to draft practical responses. If the API key is missing, invalid or rate-limited, VentureMind AI provides a labelled structured guidance fallback. This means the adviser page remains useful during local assessment while avoiding a false claim that a live AI model produced every answer. Prompt construction must avoid sending unnecessary personal data and should record the source/model version where output is persisted.",
"Live competitor analysis is similarly conditional. The platform may compose a location-aware Google Places text-search query from the business category and city, but it should only display actual business names, ratings and locations after the backend is configured with a valid GOOGLE_PLACES_API_KEY and the Places service is enabled. Google Maps may be offered as an external fallback link. Payments, email reset links, video meetings and social-media publishing are future provider integrations. Adapters and environment configuration should be used so that provider-specific code does not spread through the business domain. This boundary is a strength for maintainability, not a missing claim hidden by the interface."
],
"7.1 Current Verification": [
"Verification was carried out at several levels. Static frontend quality checks use ESLint, while the Vite production build verifies TypeScript compilation and bundling. The current workspace passed both frontend linting and production build checks. FastAPI provides interactive Swagger documentation that can be used to send valid and invalid requests during local testing. SQLAlchemy model changes are accompanied by Alembic migrations, which must be executed before server tests so that database tables match the running code. These checks offer direct evidence that the application structure is executable rather than only a design mock-up.",
"Feature verification must also include realistic role workflows. A founder should be able to create a project, persist the profile, run the deterministic evaluation, read the rationale and download a project-specific report. An administrator should be able to review a user and an advisor application without seeing plaintext sensitive documents. An advisor should see only their own bookings and change a booking status, after which the founder should receive a notification. Each manual test should record preconditions, input, expected result, actual result and pass/fail state. Screenshots and API responses may be added to the final appendix as evidence, but they should be captured from the student's verified local installation."
],
"7.2 Recommended Acceptance Test Cases": [
"Acceptance testing should prioritise the risk of broken cross-module behaviour. One test begins with a newly registered founder, creates a project and refreshes the browser at each profile stage. A passing result proves that the dashboard is using stored data instead of local-only mock state. Another test changes a meaningful profile field such as budget or target customer and reruns the evaluation; the revised score and explanation should reflect the documented rule affected. A third test creates a report and verifies the generated filename includes the startup name and readable date rather than only a database identifier.",
"Security tests should include attempts to access an administrator endpoint using a founder token, an advisor booking using a different advisor account and a shared document using an unauthorised account. These must be rejected. Migration tests should start with an empty local schema, execute alembic upgrade head and check that all expected tables exist as InnoDB. Integration tests can be added with a temporary database and HTTP test client. External services should be tested using provider sandbox keys and clear failure simulations, for example a missing Gemini key, an invalid Places key and a mail transport error. The expected behaviour is a safe message and no corrupted local record."
],
"7.3 Evaluation Criteria": [
"The platform should be assessed against effectiveness, usability, explainability, reliability and governance. Effectiveness asks whether a founder can progress from a partially specified idea to an explicit next action. Usability asks whether navigation, labels, cards and step indicators communicate what to do without expert help. Explainability asks whether users can state why a risk band was produced and what evidence would change it. Reliability asks whether data survives refresh, role boundaries hold and error states are meaningful. Governance asks whether administrator and advisor actions are traceable and sensitive data is not exposed.",
"A future study can use the System Usability Scale (SUS) after task completion, together with interviews focused on trust in AI explanations. However, numerical results must not be pre-written. The dissertation should report participant demographics appropriate to the approved study, scenario details, the exact version tested, ethical controls and limitations such as small sample size or student participants. This makes the evaluation defensible and helps distinguish a positive product demonstration from empirical evidence."
],
"8.1 Ethical Considerations": [
"Startup guidance can influence spending, employment and legal choices, so the platform must avoid overclaiming. Scores and generated suggestions should be described as decision support, not guarantees or professional advice. The user should be told when an output is a rule-based estimate, an LLM-generated text suggestion or a result from an external listing service. A founder can override or supplement profile information and should not be forced to accept an AI conclusion. Responsible messaging is especially important when a low score could discourage a person from an opportunity or a high score could encourage unsafe financial commitment.",
"The human-advisor function raises additional privacy obligations. Professional verification may require identity or qualification evidence, but collection should be limited to what is necessary. Users must receive a privacy notice and consent before uploading sensitive documents. Administrators should have restricted access; documents must not be publicly accessible or stored in plain text; and an operational retention policy should define deletion or review after a reasonable period. The project should document these controls and make clear that technical encryption does not remove the need for policy, staff training and appropriate legal compliance."
],
"8.2 Security Controls": [
"Authentication is based on password hashing and JWTs rather than storing or transmitting reusable plaintext passwords. Access control must be enforced in FastAPI dependencies and service methods, not just hidden in the frontend menu. Pydantic schemas validate input types and required fields, while database constraints support uniqueness and ownership. Error responses should be sufficiently general to avoid account enumeration in password-reset flows. Secrets such as JWT signing values, Gemini keys, Places keys, document-encryption keys and provider credentials should be loaded from environment variables and excluded from version control.",
"Additional production controls include HTTPS, secure cookie/token handling where applicable, rate limits on login and reset endpoints, malware scanning of uploaded documents, file-type and size restrictions, backups, log monitoring and an incident-response process. OWASP (2021) provides a useful baseline for evaluating these controls. The final project should be honest about which controls are implemented locally and which require deployment infrastructure. A robust local prototype can demonstrate the architecture and validation paths while reserving hosted controls such as managed key vaults, WAF rules and centralised monitoring for future work."
],
"8.3 Current Limitations": [
"The main limitation is that the risk engine is an explainable rules-based prototype, not a statistically validated predictor of startup success. It is appropriate for illustrating decision support but cannot make causal or investment claims. A valid predictive model would require a sufficiently large, representative and ethically obtained dataset, stable outcome definitions and continuing monitoring after deployment. The system also depends on founder-provided evidence, which may be incomplete, optimistic or outdated. The user interface therefore needs to encourage validation rather than reward persuasive wording.",
"The local deployment has other practical constraints. Real competitor results depend on an enabled Places API key. Real email delivery, video links, calendar invitations and payments require separate accounts, policies and provider testing. The advisor directory needs genuine vetting processes before external users rely on it. Database migrations must be applied as a controlled release step; manual edits can create schema drift. These limitations do not invalidate the project; they provide a realistic future-work roadmap and demonstrate that the student understands the gap between a well-structured academic prototype and a production SaaS service."
],
"9. Conclusion and Future Work": [
"VentureMind AI addresses the early-startup planning problem by connecting structured founder input with explainable assessment, practical planning and role-based support. Its value lies in the continuity of the user journey: a profile supplies context to evaluation, finance, requirements, legal guidance, reports and advisor conversations. The architecture combines a typed React client, FastAPI services, MySQL persistence and optional AI/integration adapters. It also treats transparency as a design feature by exposing evidence gaps and next actions instead of relying on unexplained scores.",
"The next research milestone is a documented usability and usefulness evaluation with appropriate participants. The next engineering milestone is production hardening: managed storage for documents, provider-backed email/calendar/payment flows, reliable competitor data, audit monitoring, accessibility testing and deployment automation. A later intelligent-evaluation study could compare the documented rules baseline with machine-learning models, provided that sufficient data and fairness controls are available. The project is therefore a complete foundation for a startup lifecycle management system and a credible platform for further academic research, rather than a finished commercial prediction engine."
]
}


doc = Document(PATH)
for heading, additions in sections.items():
    anchor = anchor_after_section(doc, heading)
    for addition in additions:
        anchor = add_after(anchor, addition)
doc.save(PATH)
print(PATH)
