from pathlib import Path
from docx import Document
from docx.shared import Pt

ROOT = Path(__file__).resolve().parents[1]
PATH = ROOT / "output" / "reports" / "VentureMind_AI_Final_Project_Report.docx"
doc = Document(PATH)

def insert_before(anchor, text, style="Normal"):
    p = doc.add_paragraph(text, style=style)
    p.paragraph_format.space_after = Pt(7)
    anchor._p.addprevious(p._p)
    return p

# Remove the two accidental duplicate conclusion paragraphs placed after the table of contents.
for p in list(doc.paragraphs):
    if p.text.startswith("VentureMind AI addresses the early-startup planning problem") or p.text.startswith("The next research milestone is a documented usability"):
        p._element.getparent().remove(p._element)

chapter3 = next(p for p in doc.paragraphs if p.style.name == "Heading 1" and p.text == "3. Methodology and Project Planning")
insert_before(chapter3, "2.4 Trust, AI Governance and Local Deployment", "Heading 2")
insert_before(chapter3, "Trust in AI-assisted decision support depends on more than a visually attractive chatbot. Users need to know what data has been used, whether an output is generated by deterministic rules or a language model, what limitations apply and how they can challenge a result. The OECD (2019) principles emphasise human-centred values, transparency, robustness and accountability for trustworthy AI. In VentureMind AI these principles are translated into concrete interface and architecture choices: a founder sees factors behind a score; live integrations are explicitly labelled; a human-advisor route is available for matters outside the platform's competence; and administrators have audit-oriented controls for sensitive actions. The system therefore treats AI as a bounded assistant rather than an autonomous authority.")
insert_before(chapter3, "The NIST AI Risk Management Framework also encourages organisations to govern, map, measure and manage AI risks throughout a system lifecycle (NIST, 2023). For this prototype, governance begins with scope: the risk engine makes no claim to forecast commercial success, and generated recommendations are framed as hypotheses to validate. Mapping identifies stakeholders such as founders, advisors and administrators, along with harms such as misleading financial confidence, privacy exposure and unfair advisor verification. Measurement includes reproducibility of rule-based scores, validation of API payloads and future usability testing. Management includes fallbacks when providers are unavailable, role restrictions, environment-held secrets and planned monitoring. This framework gives the literature review a direct connection to the implementation rather than treating AI ethics as a separate policy paragraph.")
insert_before(chapter3, "A local-first architecture also has educational and practical value. It permits the system to be demonstrated using React, FastAPI and MySQL on a student machine, allows database records to be inspected in phpMyAdmin or MySQL Workbench, and avoids dependency on a cloud service during a viva. At the same time, local operation does not reduce the responsibility to handle data safely. Development settings, sample accounts and debug output must never be confused with production controls. The deployment design therefore reserves external-provider adapters, HTTPS, managed object storage, central logging and secure secret management for a later production phase. This staged approach is realistic for a final-year dissertation because it shows both what is operational now and how the architecture can mature.")

appendix = next(p for p in doc.paragraphs if p.style.name == "Heading 1" and p.text == "Appendix A: Local Installation and Execution")
for ref in [
    "NIST (2023) Artificial Intelligence Risk Management Framework (AI RMF 1.0). National Institute of Standards and Technology. Available at: https://www.nist.gov/itl/ai-risk-management-framework (Accessed: 18 August 2026).",
    "OECD (2019) Recommendation of the Council on Artificial Intelligence. Available at: https://legalinstruments.oecd.org/en/instruments/OECD-LEGAL-0449 (Accessed: 18 August 2026).",
]:
    insert_before(appendix, ref, "List Bullet")

doc.save(PATH)
print(PATH)
